// @ts-nocheck
// Powered by cpt-hedge.com — data licensed per partnership agreement.
// AUTO-GENERATED by scripts/sync-hedge-data.mjs — DO NOT EDIT BY HAND.
// Source: /api/data/drone/parts + /api/data/drone/chips
// Re-run sync script after game patches to refresh data.

// lwtDroneData.ts
// Drone upgrade costs: parts (300 levels) + skill chips (10 levels).

// ─── DRONE PARTS ─────────────────────────────────────────────────────────────

export type DronePartsLevel = any;
export type DroneChipLevel = any;

export const DRONE_CHIP_LEVELS: any[] = [];

export const DRONE_CHIP_META = {
  "maxLevel": 10,
  "totalChipsForMaxLevel": 133
};

// ─── AGGREGATE HELPERS ───────────────────────────────────────────────────────

export function droneBattleDataToLevel(targetLevel: number): number {
  return DRONE_PARTS_LEVELS
    .filter((l: any) => l.level <= targetLevel)
    .reduce((sum: any, l: any) => sum + l.battleData, 0);
}

export function dronePartsToLevel(targetLevel: number): number {
  return DRONE_PARTS_LEVELS
    .filter((l: any) => l.level <= targetLevel)
    .reduce((sum: any, l: any) => sum + l.droneParts, 0);
}

export function droneChipsToLevel(targetLevel: number): number {
  return DRONE_CHIP_LEVELS
    .filter((l: any) => l.level <= targetLevel)
    .reduce((sum: any, l: any) => sum + l.chips, 0);
}

export function getDroneDataSummary(): string {
  const totalParts = DRONE_PARTS_LEVELS.reduce((s: any, l: any) => s + l.droneParts, 0);
  const totalBD   = DRONE_PARTS_LEVELS.reduce((s: any, l: any) => s + l.battleData, 0);
  const breakpoints = [50, 100, 150, 200, 250, 300]
    .filter(lvl => lvl <= DRONE_PARTS_LEVELS.length)
    .map(lvl => `  Level ${lvl}: ${dronePartsToLevel(lvl).toLocaleString()} Parts + ${droneBattleDataToLevel(lvl).toLocaleString()} Battle Data`)
    .join('\n');
  const specialStr = DRONE_SPECIAL_UNLOCKS.length
    ? DRONE_SPECIAL_UNLOCKS.map((u: any) => `  Level ${u.level}: ${u.description}`).join('\n')
    : '  None documented';
  return `=== DRONE DATA (Powered by cpt-hedge.com) ===

Total levels: ${DRONE_PARTS_LEVELS.length}
To max: ${totalParts.toLocaleString()} Drone Parts + ${totalBD.toLocaleString()} Battle Data

Cumulative cost breakpoints:
${breakpoints}

Special unlocks:
${specialStr}

Skill Chips — max level: ${DRONE_CHIP_META.maxLevel}
Total chips to max: ${DRONE_CHIP_META.totalChipsForMaxLevel}
Per-level cost: ${DRONE_CHIP_LEVELS.map(l => `L${l.level}:${l.chips}`).join(' | ')}`;
}
