// @ts-nocheck
// Powered by cpt-hedge.com — data licensed per partnership agreement.
// AUTO-GENERATED by scripts/sync-hedge-data.mjs — DO NOT EDIT BY HAND.
// Source: /api/data/hero/exp + /api/data/hero/shards + /api/data/hero/weapon-shards + /api/data/hero/gear + /api/data/hero/skill-medals
// Re-run sync script after game patches to refresh data.

// lwtHeroCostData.ts
// Hero upgrade costs: XP, shards, weapon shards, gear, skill medals.

// ─── HERO EXP ─────────────────────────────────────────────────────────────────
// XP required per level (1–175) + minimum HQ level gate per hero level.

export interface HeroExpLevel {
  level: number; xpRequired: number; minHq?: number;
}

export const HERO_EXP_LEVELS: HeroExpLevel[] = [
  {
    "heroLevel": 1,
    "experience": 100,
    "hqLevel": 1
  },
  {
    "heroLevel": 2,
    "experience": 200,
    "hqLevel": 1
  },
  {
    "heroLevel": 3,
    "experience": 300,
    "hqLevel": 1
  },
  {
    "heroLevel": 4,
    "experience": 400,
    "hqLevel": 1
  },
  {
    "heroLevel": 5,
    "experience": 500,
    "hqLevel": 2
  },
  {
    "heroLevel": 6,
    "experience": 600,
    "hqLevel": 2
  },
  {
    "heroLevel": 7,
    "experience": 700,
    "hqLevel": 2
  },
  {
    "heroLevel": 8,
    "experience": 800,
    "hqLevel": 2
  },
  {
    "heroLevel": 9,
    "experience": 900,
    "hqLevel": 2
  },
  {
    "heroLevel": 10,
    "experience": 1000,
    "hqLevel": 3
  },
  {
    "heroLevel": 11,
    "experience": 1100,
    "hqLevel": 3
  },
  {
    "heroLevel": 12,
    "experience": 1200,
    "hqLevel": 3
  },
  {
    "heroLevel": 13,
    "experience": 1300,
    "hqLevel": 3
  },
  {
    "heroLevel": 14,
    "experience": 1400,
    "hqLevel": 3
  },
  {
    "heroLevel": 15,
    "experience": 1500,
    "hqLevel": 4
  },
  {
    "heroLevel": 16,
    "experience": 1600,
    "hqLevel": 4
  },
  {
    "heroLevel": 17,
    "experience": 1700,
    "hqLevel": 4
  },
  {
    "heroLevel": 18,
    "experience": 1800,
    "hqLevel": 4
  },
  {
    "heroLevel": 19,
    "experience": 1900,
    "hqLevel": 4
  },
  {
    "heroLevel": 20,
    "experience": 2000,
    "hqLevel": 5
  },
  {
    "heroLevel": 21,
    "experience": 2100,
    "hqLevel": 5
  },
  {
    "heroLevel": 22,
    "experience": 2300,
    "hqLevel": 5
  },
  {
    "heroLevel": 23,
    "experience": 2700,
    "hqLevel": 5
  },
  {
    "heroLevel": 24,
    "experience": 3200,
    "hqLevel": 5
  },
  {
    "heroLevel": 25,
    "experience": 3900,
    "hqLevel": 6
  },
  {
    "heroLevel": 26,
    "experience": 4600,
    "hqLevel": 6
  },
  {
    "heroLevel": 27,
    "experience": 5500,
    "hqLevel": 6
  },
  {
    "heroLevel": 28,
    "experience": 6600,
    "hqLevel": 6
  },
  {
    "heroLevel": 29,
    "experience": 8000,
    "hqLevel": 6
  },
  {
    "heroLevel": 30,
    "experience": 9500,
    "hqLevel": 7
  },
  {
    "heroLevel": 31,
    "experience": 12000,
    "hqLevel": 7
  },
  {
    "heroLevel": 32,
    "experience": 14000,
    "hqLevel": 7
  },
  {
    "heroLevel": 33,
    "experience": 17000,
    "hqLevel": 7
  },
  {
    "heroLevel": 34,
    "experience": 20000,
    "hqLevel": 7
  },
  {
    "heroLevel": 35,
    "experience": 24000,
    "hqLevel": 8
  },
  {
    "heroLevel": 36,
    "experience": 29000,
    "hqLevel": 8
  },
  {
    "heroLevel": 37,
    "experience": 35000,
    "hqLevel": 8
  },
  {
    "heroLevel": 38,
    "experience": 41000,
    "hqLevel": 8
  },
  {
    "heroLevel": 39,
    "experience": 49000,
    "hqLevel": 8
  },
  {
    "heroLevel": 40,
    "experience": 59000,
    "hqLevel": 9
  },
  {
    "heroLevel": 41,
    "experience": 71000,
    "hqLevel": 9
  },
  {
    "heroLevel": 42,
    "experience": 85000,
    "hqLevel": 9
  },
  {
    "heroLevel": 43,
    "experience": 110000,
    "hqLevel": 9
  },
  {
    "heroLevel": 44,
    "experience": 130000,
    "hqLevel": 9
  },
  {
    "heroLevel": 45,
    "experience": 150000,
    "hqLevel": 10
  },
  {
    "heroLevel": 46,
    "experience": 180000,
    "hqLevel": 10
  },
  {
    "heroLevel": 47,
    "experience": 220000,
    "hqLevel": 10
  },
  {
    "heroLevel": 48,
    "experience": 260000,
    "hqLevel": 10
  },
  {
    "heroLevel": 49,
    "experience": 310000,
    "hqLevel": 10
  },
  {
    "heroLevel": 50,
    "experience": 370000,
    "hqLevel": 11
  },
  {
    "heroLevel": 51,
    "experience": 440000,
    "hqLevel": 11
  },
  {
    "heroLevel": 52,
    "experience": 530000,
    "hqLevel": 11
  },
  {
    "heroLevel": 53,
    "experience": 630000,
    "hqLevel": 11
  },
  {
    "heroLevel": 54,
    "experience": 760000,
    "hqLevel": 11
  },
  {
    "heroLevel": 55,
    "experience": 910000,
    "hqLevel": 12
  },
  {
    "heroLevel": 56,
    "experience": 1100000,
    "hqLevel": 12
  },
  {
    "heroLevel": 57,
    "experience": 1400000,
    "hqLevel": 12
  },
  {
    "heroLevel": 58,
    "experience": 1600000,
    "hqLevel": 12
  },
  {
    "heroLevel": 59,
    "experience": 1900000,
    "hqLevel": 12
  },
  {
    "heroLevel": 60,
    "experience": 2100000,
    "hqLevel": 13
  },
  {
    "heroLevel": 61,
    "experience": 2300000,
    "hqLevel": 13
  },
  {
    "heroLevel": 62,
    "experience": 2500000,
    "hqLevel": 13
  },
  {
    "heroLevel": 63,
    "experience": 2800000,
    "hqLevel": 13
  },
  {
    "heroLevel": 64,
    "experience": 3100000,
    "hqLevel": 13
  },
  {
    "heroLevel": 65,
    "experience": 3400000,
    "hqLevel": 14
  },
  {
    "heroLevel": 66,
    "experience": 3700000,
    "hqLevel": 14
  },
  {
    "heroLevel": 67,
    "experience": 4100000,
    "hqLevel": 14
  },
  {
    "heroLevel": 68,
    "experience": 4500000,
    "hqLevel": 14
  },
  {
    "heroLevel": 69,
    "experience": 4900000,
    "hqLevel": 14
  },
  {
    "heroLevel": 70,
    "experience": 5400000,
    "hqLevel": 15
  },
  {
    "heroLevel": 71,
    "experience": 5900000,
    "hqLevel": 15
  },
  {
    "heroLevel": 72,
    "experience": 6500000,
    "hqLevel": 15
  },
  {
    "heroLevel": 73,
    "experience": 7200000,
    "hqLevel": 15
  },
  {
    "heroLevel": 74,
    "experience": 7900000,
    "hqLevel": 15
  },
  {
    "heroLevel": 75,
    "experience": 8700000,
    "hqLevel": 16
  },
  {
    "heroLevel": 76,
    "experience": 9500000,
    "hqLevel": 16
  },
  {
    "heroLevel": 77,
    "experience": 11000000,
    "hqLevel": 16
  },
  {
    "heroLevel": 78,
    "experience": 12000000,
    "hqLevel": 16
  },
  {
    "heroLevel": 79,
    "experience": 13000000,
    "hqLevel": 16
  },
  {
    "heroLevel": 80,
    "experience": 13000000,
    "hqLevel": 17
  },
  {
    "heroLevel": 81,
    "experience": 14000000,
    "hqLevel": 17
  },
  {
    "heroLevel": 82,
    "experience": 14000000,
    "hqLevel": 17
  },
  {
    "heroLevel": 83,
    "experience": 15000000,
    "hqLevel": 17
  },
  {
    "heroLevel": 84,
    "experience": 16000000,
    "hqLevel": 17
  },
  {
    "heroLevel": 85,
    "experience": 17000000,
    "hqLevel": 18
  },
  {
    "heroLevel": 86,
    "experience": 18000000,
    "hqLevel": 18
  },
  {
    "heroLevel": 87,
    "experience": 19000000,
    "hqLevel": 18
  },
  {
    "heroLevel": 88,
    "experience": 20000000,
    "hqLevel": 18
  },
  {
    "heroLevel": 89,
    "experience": 21000000,
    "hqLevel": 18
  },
  {
    "heroLevel": 90,
    "experience": 22000000,
    "hqLevel": 19
  },
  {
    "heroLevel": 91,
    "experience": 23000000,
    "hqLevel": 19
  },
  {
    "heroLevel": 92,
    "experience": 24000000,
    "hqLevel": 19
  },
  {
    "heroLevel": 93,
    "experience": 25000000,
    "hqLevel": 19
  },
  {
    "heroLevel": 94,
    "experience": 26000000,
    "hqLevel": 19
  },
  {
    "heroLevel": 95,
    "experience": 27000000,
    "hqLevel": 20
  },
  {
    "heroLevel": 96,
    "experience": 28000000,
    "hqLevel": 20
  },
  {
    "heroLevel": 97,
    "experience": 30000000,
    "hqLevel": 20
  },
  {
    "heroLevel": 98,
    "experience": 31000000,
    "hqLevel": 20
  },
  {
    "heroLevel": 99,
    "experience": 33000000,
    "hqLevel": 20
  },
  {
    "heroLevel": 100,
    "experience": 35000000,
    "hqLevel": 21
  },
  {
    "heroLevel": 101,
    "experience": 37000000,
    "hqLevel": 21
  },
  {
    "heroLevel": 102,
    "experience": 39000000,
    "hqLevel": 21
  },
  {
    "heroLevel": 103,
    "experience": 41000000,
    "hqLevel": 21
  },
  {
    "heroLevel": 104,
    "experience": 43000000,
    "hqLevel": 21
  },
  {
    "heroLevel": 105,
    "experience": 45000000,
    "hqLevel": 22
  },
  {
    "heroLevel": 106,
    "experience": 47000000,
    "hqLevel": 22
  },
  {
    "heroLevel": 107,
    "experience": 49000000,
    "hqLevel": 22
  },
  {
    "heroLevel": 108,
    "experience": 51000000,
    "hqLevel": 22
  },
  {
    "heroLevel": 109,
    "experience": 53000000,
    "hqLevel": 22
  },
  {
    "heroLevel": 110,
    "experience": 55000000,
    "hqLevel": 23
  },
  {
    "heroLevel": 111,
    "experience": 57000000,
    "hqLevel": 23
  },
  {
    "heroLevel": 112,
    "experience": 59000000,
    "hqLevel": 23
  },
  {
    "heroLevel": 113,
    "experience": 61000000,
    "hqLevel": 23
  },
  {
    "heroLevel": 114,
    "experience": 63000000,
    "hqLevel": 23
  },
  {
    "heroLevel": 115,
    "experience": 65000000,
    "hqLevel": 24
  },
  {
    "heroLevel": 116,
    "experience": 67000000,
    "hqLevel": 24
  },
  {
    "heroLevel": 117,
    "experience": 69000000,
    "hqLevel": 24
  },
  {
    "heroLevel": 118,
    "experience": 71000000,
    "hqLevel": 24
  },
  {
    "heroLevel": 119,
    "experience": 73000000,
    "hqLevel": 24
  },
  {
    "heroLevel": 120,
    "experience": 75000000,
    "hqLevel": 25
  },
  {
    "heroLevel": 121,
    "experience": 77000000,
    "hqLevel": 25
  },
  {
    "heroLevel": 122,
    "experience": 79000000,
    "hqLevel": 25
  },
  {
    "heroLevel": 123,
    "experience": 81000000,
    "hqLevel": 25
  },
  {
    "heroLevel": 124,
    "experience": 83000000,
    "hqLevel": 25
  },
  {
    "heroLevel": 125,
    "experience": 85000000,
    "hqLevel": 26
  },
  {
    "heroLevel": 126,
    "experience": 87000000,
    "hqLevel": 26
  },
  {
    "heroLevel": 127,
    "experience": 89000000,
    "hqLevel": 26
  },
  {
    "heroLevel": 128,
    "experience": 91000000,
    "hqLevel": 26
  },
  {
    "heroLevel": 129,
    "experience": 93000000,
    "hqLevel": 26
  },
  {
    "heroLevel": 130,
    "experience": 95000000,
    "hqLevel": 27
  },
  {
    "heroLevel": 131,
    "experience": 97000000,
    "hqLevel": 27
  },
  {
    "heroLevel": 132,
    "experience": 100000000,
    "hqLevel": 27
  },
  {
    "heroLevel": 133,
    "experience": 105000000,
    "hqLevel": 27
  },
  {
    "heroLevel": 134,
    "experience": 110000000,
    "hqLevel": 27
  },
  {
    "heroLevel": 135,
    "experience": 115000000,
    "hqLevel": 28
  },
  {
    "heroLevel": 136,
    "experience": 120000000,
    "hqLevel": 28
  },
  {
    "heroLevel": 137,
    "experience": 125000000,
    "hqLevel": 28
  },
  {
    "heroLevel": 138,
    "experience": 130000000,
    "hqLevel": 28
  },
  {
    "heroLevel": 139,
    "experience": 135000000,
    "hqLevel": 28
  },
  {
    "heroLevel": 140,
    "experience": 140000000,
    "hqLevel": 29
  },
  {
    "heroLevel": 141,
    "experience": 145000000,
    "hqLevel": 29
  },
  {
    "heroLevel": 142,
    "experience": 150000000,
    "hqLevel": 29
  },
  {
    "heroLevel": 143,
    "experience": 155000000,
    "hqLevel": 29
  },
  {
    "heroLevel": 144,
    "experience": 160000000,
    "hqLevel": 29
  },
  {
    "heroLevel": 145,
    "experience": 165000000,
    "hqLevel": 30
  },
  {
    "heroLevel": 146,
    "experience": 170000000,
    "hqLevel": 30
  },
  {
    "heroLevel": 147,
    "experience": 175000000,
    "hqLevel": 30
  },
  {
    "heroLevel": 148,
    "experience": 180000000,
    "hqLevel": 30
  },
  {
    "heroLevel": 149,
    "experience": 185000000,
    "hqLevel": 30
  },
  {
    "heroLevel": 150,
    "experience": 200000000,
    "hqLevel": 31
  },
  {
    "heroLevel": 151,
    "experience": 215000000,
    "hqLevel": 31
  },
  {
    "heroLevel": 152,
    "experience": 230000000,
    "hqLevel": 31
  },
  {
    "heroLevel": 153,
    "experience": 245000000,
    "hqLevel": 31
  },
  {
    "heroLevel": 154,
    "experience": 260000000,
    "hqLevel": 31
  },
  {
    "heroLevel": 155,
    "experience": 275000000,
    "hqLevel": 32
  },
  {
    "heroLevel": 156,
    "experience": 290000000,
    "hqLevel": 32
  },
  {
    "heroLevel": 157,
    "experience": 305000000,
    "hqLevel": 32
  },
  {
    "heroLevel": 158,
    "experience": 320000000,
    "hqLevel": 32
  },
  {
    "heroLevel": 159,
    "experience": 335000000,
    "hqLevel": 32
  },
  {
    "heroLevel": 160,
    "experience": 350000000,
    "hqLevel": 33
  },
  {
    "heroLevel": 161,
    "experience": 365000000,
    "hqLevel": 33
  },
  {
    "heroLevel": 162,
    "experience": 380000000,
    "hqLevel": 33
  },
  {
    "heroLevel": 163,
    "experience": 395000000,
    "hqLevel": 33
  },
  {
    "heroLevel": 164,
    "experience": 410000000,
    "hqLevel": 33
  },
  {
    "heroLevel": 165,
    "experience": 435000000,
    "hqLevel": 34
  },
  {
    "heroLevel": 166,
    "experience": 460000000,
    "hqLevel": 34
  },
  {
    "heroLevel": 167,
    "experience": 485000000,
    "hqLevel": 34
  },
  {
    "heroLevel": 168,
    "experience": 510000000,
    "hqLevel": 34
  },
  {
    "heroLevel": 169,
    "experience": 535000000,
    "hqLevel": 34
  },
  {
    "heroLevel": 170,
    "experience": 560000000,
    "hqLevel": 35
  },
  {
    "heroLevel": 171,
    "experience": 585000000,
    "hqLevel": 35
  },
  {
    "heroLevel": 172,
    "experience": 610000000,
    "hqLevel": 35
  },
  {
    "heroLevel": 173,
    "experience": 635000000,
    "hqLevel": 35
  },
  {
    "heroLevel": 174,
    "experience": 660000000,
    "hqLevel": 35
  },
  {
    "heroLevel": 175,
    "experience": 0,
    "hqLevel": 35
  }
];

export const HERO_EXP_META = {
  "total": 175,
  "minLevel": 1,
  "maxLevel": 175
};

// ─── HERO SHARDS ─────────────────────────────────────────────────────────────
// Shard requirements per star upgrade.
// regular — UR, SSR, SR heroes (0* → 5*)
// ssr     — Upgraded SSR heroes to UR (3* → 5*) — double the regular quantity

export interface HeroShardTier {
  fromStar: number; toStar: number; shards: number;
}

export const HERO_SHARDS_REGULAR: HeroShardTier[] = [
  {
    "starFrom": 0,
    "starTo": 1,
    "tierShards": 5,
    "tiers": 5,
    "totalShards": 25
  },
  {
    "starFrom": 1,
    "starTo": 2,
    "tierShards": 10,
    "tiers": 5,
    "totalShards": 50
  },
  {
    "starFrom": 2,
    "starTo": 3,
    "tierShards": 20,
    "tiers": 5,
    "totalShards": 100
  },
  {
    "starFrom": 3,
    "starTo": 4,
    "tierShards": 60,
    "tiers": 5,
    "totalShards": 300
  },
  {
    "starFrom": 4,
    "starTo": 5,
    "tierShards": 100,
    "tiers": 5,
    "totalShards": 500
  }
];

export const HERO_SHARDS_SSR: HeroShardTier[] = [
  {
    "starFrom": 3,
    "starTo": 4,
    "tierShards": 120,
    "tiers": 5,
    "totalShards": 600
  },
  {
    "starFrom": 4,
    "starTo": 5,
    "tierShards": 200,
    "tiers": 5,
    "totalShards": 1000
  }
];

export const HERO_SHARDS_META = {
  "note": "'regular' covers UR heroes (all stars 0-5). 'ssr' covers SSR heroes (stars 3-5 only). Each entry represents one full star upgrade (5 tiers)."
};

// ─── WEAPON SHARDS ───────────────────────────────────────────────────────────
// Weapon shard costs per level segment, max level, and total cost to max.

export interface WeaponShardSegment {
  fromLevel: number; toLevel: number; shardsPerLevel: number; totalShards: number;
}

export const WEAPON_SHARD_SEGMENTS: WeaponShardSegment[] = [
  {
    "description": "unlock weapon lvl.1",
    "minLevel": 0,
    "maxLevel": 1,
    "shardsPerLevel": 50,
    "totalForSegment": 50
  },
  {
    "description": "level 2-5",
    "minLevel": 1,
    "maxLevel": 5,
    "shardsPerLevel": 20,
    "totalForSegment": 80
  },
  {
    "description": "level 6-10",
    "minLevel": 5,
    "maxLevel": 10,
    "shardsPerLevel": 40,
    "totalForSegment": 200
  },
  {
    "description": "level 11-15",
    "minLevel": 10,
    "maxLevel": 15,
    "shardsPerLevel": 60,
    "totalForSegment": 300
  },
  {
    "description": "level 16-20",
    "minLevel": 15,
    "maxLevel": 20,
    "shardsPerLevel": 100,
    "totalForSegment": 500
  },
  {
    "description": "level 21-25",
    "minLevel": 20,
    "maxLevel": 25,
    "shardsPerLevel": 150,
    "totalForSegment": 750
  },
  {
    "description": "level 26-30",
    "minLevel": 25,
    "maxLevel": 30,
    "shardsPerLevel": 200,
    "totalForSegment": 1000
  }
];

export const WEAPON_SHARD_META = {
  "totalSegments": 7,
  "note": "Each segment covers a range of levels with a fixed shard cost per level."
};

// ─── GEAR ────────────────────────────────────────────────────────────────────
// Gear upgrade costs by level and by star for each rarity (UR, SSR, SR).

export interface GearLevel {
  level: number; materials: number; [key: string]: unknown;
}
export interface GearStarUpgrade {
  fromStar: number; toStar: number; materials: number;
}
export interface GearRarity {
  rarity: string; levels: GearLevel[]; starUpgrades: GearStarUpgrade[];
}

export const GEAR_BY_RARITY: GearRarity[] = [];

export const GEAR_META = {
  "note": "'levels' contains per-level upgrade costs (gold + ore) for each rarity tier. 'stars' contains star upgrade costs (gold, ore, dielectric ceramic, and gear blueprints).",
  "rarities": [
    "UR",
    "SSR",
    "SR"
  ]
};

// ─── SKILL MEDALS ────────────────────────────────────────────────────────────
// Skill medal costs per level upgrade for UR, SSR, and SR heroes.

export interface SkillMedalLevel {
  level: number; medals: number;
}
export interface SkillMedalRarity {
  rarity: string; levels: SkillMedalLevel[];
}

export const SKILL_MEDALS_BY_RARITY: SkillMedalRarity[] = [];

export const SKILL_MEDALS_META = {
  "note": "Each array contains the medal cost per skill level upgrade, indexed from level 1. UR has 39 upgrades (max level 40), SSR has 29 (max 30), SR has 30 (max 30).",
  "maxLevels": {
    "UR": 40,
    "SSR": 30,
    "SR": 30
  }
};

// ─── AGGREGATE HELPERS ───────────────────────────────────────────────────────

export function heroXpToLevel(targetLevel: number): number {
  return HERO_EXP_LEVELS
    .filter(l => (l.heroLevel ?? l.level) <= targetLevel)
    .reduce((sum, l) => sum + (l.experience ?? l.xpRequired ?? 0), 0);
}

export function heroShardsToStar(targetStar: number, type: 'regular' | 'ssr' = 'regular'): number {
  const tiers = type === 'ssr' ? HERO_SHARDS_SSR : HERO_SHARDS_REGULAR;
  return tiers
    .filter(t => (t.starTo ?? t.toStar) <= targetStar)
    .reduce((sum, t) => sum + (t.totalShards ?? t.shards ?? 0), 0);
}

export function weaponShardsToLevel(targetLevel: number): number {
  return WEAPON_SHARD_SEGMENTS
    .filter(s => (s.maxLevel ?? s.toLevel) <= targetLevel)
    .reduce((sum, s) => sum + (s.totalForSegment ?? s.totalShards ?? 0), 0);
}

export function skillMedalsToLevel(targetLevel: number, rarity: string): number {
  if (!SKILL_MEDALS_BY_RARITY.length) return 0;
  const rarityData = SKILL_MEDALS_BY_RARITY.find(r => r.rarity.toLowerCase() === rarity.toLowerCase());
  if (!rarityData) return 0;
  return rarityData.levels
    .filter(l => l.level <= targetLevel)
    .reduce((sum, l) => sum + l.medals, 0);
}

export function getHeroCostDataSummary(): string {
  const maxHeroLevel = HERO_EXP_META.maxLevel ?? HERO_EXP_LEVELS[HERO_EXP_LEVELS.length - 1]?.heroLevel ?? 175;
  const totalXpToMax = heroXpToLevel(Number(maxHeroLevel));

  const shardRows = HERO_SHARDS_REGULAR.map(t =>
    `  ${t.starFrom ?? t.fromStar}* → ${t.starTo ?? t.toStar}*: ${(t.totalShards ?? t.shards ?? 0).toLocaleString()} shards (regular)`
  ).join('\n');

  const weaponTotal = WEAPON_SHARD_SEGMENTS.reduce((s, seg) => s + (seg.totalForSegment ?? seg.totalShards ?? 0), 0);

  const gearRows = GEAR_BY_RARITY.length
    ? GEAR_BY_RARITY.map(r => `  ${r.rarity}: ${r.levels.length} levels, ${r.starUpgrades.length} star upgrades`).join('\n')
    : '  (data pending sync)';

  const medalRows = SKILL_MEDALS_BY_RARITY.length
    ? SKILL_MEDALS_BY_RARITY.map(r => {
        const total = r.levels.reduce((s, l) => s + l.medals, 0);
        return `  ${r.rarity}: ${total.toLocaleString()} medals to max`;
      }).join('\n')
    : '  (data pending sync)';

  return `=== HERO COST DATA (Powered by cpt-hedge.com) ===

Hero XP — max level: ${maxHeroLevel}
Total XP to max: ${totalXpToMax.toLocaleString()}

Hero Shards (0* → 5*):
${shardRows}

Weapon Shards — max level: 30
Total weapon shards to max: ${weaponTotal.toLocaleString()}

Gear upgrade costs by rarity:
${gearRows}

Skill Medals to max by rarity:
${medalRows}`;
}