// @ts-nocheck
// Powered by cpt-hedge.com — data licensed per partnership agreement.
// AUTO-GENERATED by scripts/sync-hedge-data.mjs — DO NOT EDIT BY HAND.
// Source: /api/data/stores/packs + /api/data/stores/passes + /api/data/stores/currencies
// Re-run sync script after game patches to refresh data.

// lwtPackData.ts
// Tiered daily packs, one-time packs, battle passes, brick-to-fiat currency table.

// ─── TYPES ───────────────────────────────────────────────────────────────────

export interface PackItem { name: string; amount: number; }
export interface PackTier { priceInBricks: number; items: PackItem[]; }
export interface TieredPack {
  id: string; name: string; availability: string; availabilityType: string;
  tiers: PackTier[];
}
export interface FlatPack {
  id: string; name: string; availability: number | string;
  priceInBricks: number; items: PackItem[];
}
export interface PassTier { name: string; priceInBricks: number; items: PackItem[]; }
export interface BattlePass { id: string; name: string; rotation: string; tiers: PassTier[]; }
export interface BrickCurrency { currency: string; bricksPerUnit: number; unitsPerBrick: number; }

// ─── TIERED DAILY / ONE-TIME PACKS ───────────────────────────────────────────

export const TIERED_PACKS: TieredPack[] = [
  {
    "id": "monday-drone-great-value",
    "name": "Drone Great Value Pack",
    "availability": "Monday",
    "availabilityType": "daily",
    "tiers": [
      {
        "priceInBricks": 500,
        "items": [
          {
            "name": "Drone Parts",
            "amount": 20
          },
          {
            "name": "Battle Data 10K",
            "amount": 4
          },
          {
            "name": "Skill Chip Chest (SR)",
            "amount": 1
          }
        ]
      },
      {
        "priceInBricks": 1000,
        "items": [
          {
            "name": "Drone Parts",
            "amount": 30
          },
          {
            "name": "Battle Data 10K",
            "amount": 8
          },
          {
            "name": "Skill Chip Chest (SSR)",
            "amount": 1
          }
        ]
      },
      {
        "priceInBricks": 2000,
        "items": [
          {
            "name": "Drone Parts",
            "amount": 60
          },
          {
            "name": "Battle Data 10K",
            "amount": 16
          },
          {
            "name": "Skill Chip Chest (SSR)",
            "amount": 2
          }
        ]
      },
      {
        "priceInBricks": 5000,
        "items": [
          {
            "name": "Drone Parts",
            "amount": 150
          },
          {
            "name": "Battle Data 10K",
            "amount": 40
          },
          {
            "name": "Skill Chip Chest (SSR)",
            "amount": 4
          }
        ]
      },
      {
        "priceInBricks": 10000,
        "items": [
          {
            "name": "Drone Parts",
            "amount": 300
          },
          {
            "name": "Battle Data 10K",
            "amount": 80
          },
          {
            "name": "Skill Chip Chest (UR)",
            "amount": 1
          }
        ]
      }
    ]
  },
  {
    "id": "tuesday-armament-research",
    "name": "Armament Research Pack",
    "availability": "Tuesday",
    "availabilityType": "daily",
    "tiers": [
      {
        "priceInBricks": 500,
        "items": [
          {
            "name": "Armament Core",
            "amount": 15
          },
          {
            "name": "Armament Materials",
            "amount": 25000
          },
          {
            "name": "Resource Choice Chest (UR)",
            "amount": 5
          }
        ]
      },
      {
        "priceInBricks": 1000,
        "items": [
          {
            "name": "Armament Core",
            "amount": 30
          },
          {
            "name": "Armament Materials",
            "amount": 50000
          },
          {
            "name": "Resource Choice Chest (UR)",
            "amount": 10
          }
        ]
      },
      {
        "priceInBricks": 2000,
        "items": [
          {
            "name": "Armament Core",
            "amount": 50
          },
          {
            "name": "Armament Materials",
            "amount": 100000
          },
          {
            "name": "Resource Choice Chest (UR)",
            "amount": 20
          }
        ]
      },
      {
        "priceInBricks": 5000,
        "items": [
          {
            "name": "Armament Core",
            "amount": 100
          },
          {
            "name": "Armament Materials",
            "amount": 200000
          },
          {
            "name": "Resource Choice Chest (UR)",
            "amount": 40
          }
        ]
      },
      {
        "priceInBricks": 10000,
        "items": [
          {
            "name": "Armament Core",
            "amount": 200
          },
          {
            "name": "Armament Materials",
            "amount": 400000
          },
          {
            "name": "Resource Choice Chest (UR)",
            "amount": 80
          }
        ]
      }
    ]
  },
  {
    "id": "wednesday-research-speed-up",
    "name": "Research Speed-Up Pack",
    "availability": "Wednesday",
    "availabilityType": "daily",
    "tiers": [
      {
        "priceInBricks": 500,
        "items": [
          {
            "name": "1h Research Speed-up",
            "amount": 25
          },
          {
            "name": "Coin Chest (UR)",
            "amount": 5
          }
        ]
      },
      {
        "priceInBricks": 1000,
        "items": [
          {
            "name": "1h Research Speed-up",
            "amount": 50
          },
          {
            "name": "Coin Chest (UR)",
            "amount": 10
          }
        ]
      },
      {
        "priceInBricks": 2000,
        "items": [
          {
            "name": "1h Research Speed-up",
            "amount": 100
          },
          {
            "name": "Coin Chest (UR)",
            "amount": 20
          }
        ]
      },
      {
        "priceInBricks": 5000,
        "items": [
          {
            "name": "1h Research Speed-up",
            "amount": 250
          },
          {
            "name": "Coin Chest (UR)",
            "amount": 50
          }
        ]
      },
      {
        "priceInBricks": 10000,
        "items": [
          {
            "name": "1h Research Speed-up",
            "amount": 500
          },
          {
            "name": "Coin Chest (UR)",
            "amount": 100
          }
        ]
      }
    ]
  },
  {
    "id": "thursday-hero-shard-choice",
    "name": "Hero Shard / Exclusive Weapon Shard Choice Pack",
    "availability": "Thursday",
    "availabilityType": "daily",
    "tiers": [
      {
        "priceInBricks": 500,
        "items": [
          {
            "name": "UR Hero Shard Choice Box",
            "amount": 10
          },
          {
            "name": "Skill Medal",
            "amount": 500
          }
        ]
      },
      {
        "priceInBricks": 1000,
        "items": [
          {
            "name": "UR Hero Shard Choice Box",
            "amount": 20
          },
          {
            "name": "Skill Medal",
            "amount": 1000
          }
        ]
      },
      {
        "priceInBricks": 2000,
        "items": [
          {
            "name": "UR Hero Shard Choice Box",
            "amount": 40
          },
          {
            "name": "Skill Medal",
            "amount": 2000
          }
        ]
      },
      {
        "priceInBricks": 5000,
        "items": [
          {
            "name": "UR Hero Shard Choice Box",
            "amount": 80
          },
          {
            "name": "Skill Medal",
            "amount": 4000
          }
        ]
      },
      {
        "priceInBricks": 10000,
        "items": [
          {
            "name": "UR Hero Shard Choice Box",
            "amount": 160
          },
          {
            "name": "Skill Medal",
            "amount": 8000
          }
        ]
      }
    ]
  },
  {
    "id": "friday-overlord-training-value",
    "name": "Overlord Training Value Pack",
    "availability": "Friday",
    "availabilityType": "daily",
    "tiers": [
      {
        "priceInBricks": 500,
        "items": [
          {
            "name": "Training Certificate",
            "amount": 30
          },
          {
            "name": "Training Guidebook",
            "amount": 3000
          }
        ]
      },
      {
        "priceInBricks": 1000,
        "items": [
          {
            "name": "Training Certificate",
            "amount": 50
          },
          {
            "name": "Training Guidebook",
            "amount": 6000
          }
        ]
      },
      {
        "priceInBricks": 2000,
        "items": [
          {
            "name": "Training Certificate",
            "amount": 100
          },
          {
            "name": "Training Guidebook",
            "amount": 12000
          }
        ]
      },
      {
        "priceInBricks": 5000,
        "items": [
          {
            "name": "Training Certificate",
            "amount": 200
          },
          {
            "name": "Training Guidebook",
            "amount": 30000
          }
        ]
      },
      {
        "priceInBricks": 10000,
        "items": [
          {
            "name": "Training Certificate",
            "amount": 400
          },
          {
            "name": "Training Guidebook",
            "amount": 60000
          }
        ]
      }
    ]
  },
  {
    "id": "saturday-military-training",
    "name": "Military Training Pack",
    "availability": "Saturday",
    "availabilityType": "daily",
    "tiers": [
      {
        "priceInBricks": 500,
        "items": [
          {
            "name": "5m Speed-up",
            "amount": 200
          },
          {
            "name": "Iron Chest (UR)",
            "amount": 1
          },
          {
            "name": "Food Chest (UR)",
            "amount": 1
          },
          {
            "name": "Coin Chest (UR)",
            "amount": 1
          }
        ]
      },
      {
        "priceInBricks": 1000,
        "items": [
          {
            "name": "5m Speed-up",
            "amount": 400
          },
          {
            "name": "Iron Chest (UR)",
            "amount": 2
          },
          {
            "name": "Food Chest (UR)",
            "amount": 2
          },
          {
            "name": "Coin Chest (UR)",
            "amount": 2
          }
        ]
      },
      {
        "priceInBricks": 2000,
        "items": [
          {
            "name": "5m Speed-up",
            "amount": 800
          },
          {
            "name": "Iron Chest (UR)",
            "amount": 4
          },
          {
            "name": "Food Chest (UR)",
            "amount": 4
          },
          {
            "name": "Coin Chest (UR)",
            "amount": 4
          }
        ]
      },
      {
        "priceInBricks": 5000,
        "items": [
          {
            "name": "5m Speed-up",
            "amount": 2000
          },
          {
            "name": "Iron Chest (UR)",
            "amount": 10
          },
          {
            "name": "Food Chest (UR)",
            "amount": 10
          },
          {
            "name": "Coin Chest (UR)",
            "amount": 10
          }
        ]
      },
      {
        "priceInBricks": 10000,
        "items": [
          {
            "name": "5m Speed-up",
            "amount": 4000
          },
          {
            "name": "Iron Chest (UR)",
            "amount": 20
          },
          {
            "name": "Food Chest (UR)",
            "amount": 20
          },
          {
            "name": "Coin Chest (UR)",
            "amount": 20
          }
        ]
      }
    ]
  },
  {
    "id": "sunday-gear-master",
    "name": "Gear Master Pack",
    "availability": "Sunday",
    "availabilityType": "daily",
    "tiers": [
      {
        "priceInBricks": 500,
        "items": [
          {
            "name": "Upgrade Ore Lucky Chest",
            "amount": 1
          },
          {
            "name": "Upgrade Ore",
            "amount": 1500
          }
        ]
      },
      {
        "priceInBricks": 1000,
        "items": [
          {
            "name": "Upgrade Ore Lucky Chest",
            "amount": 2
          },
          {
            "name": "Upgrade Ore",
            "amount": 3000
          }
        ]
      },
      {
        "priceInBricks": 2000,
        "items": [
          {
            "name": "Upgrade Ore Lucky Chest",
            "amount": 4
          },
          {
            "name": "Upgrade Ore",
            "amount": 6000
          }
        ]
      },
      {
        "priceInBricks": 5000,
        "items": [
          {
            "name": "Upgrade Ore Lucky Chest",
            "amount": 8
          },
          {
            "name": "Upgrade Ore",
            "amount": 12000
          }
        ]
      },
      {
        "priceInBricks": 10000,
        "items": [
          {
            "name": "Upgrade Ore Lucky Chest",
            "amount": 16
          },
          {
            "name": "Upgrade Ore",
            "amount": 24000
          }
        ]
      }
    ]
  },
  {
    "id": "weekly-drone-combat-boost-exp",
    "name": "Drone Combat Boost EXP Pack",
    "availability": "Weekly",
    "availabilityType": "weekly",
    "tiers": [
      {
        "priceInBricks": 500,
        "items": [
          {
            "name": "Drone Combat Boost EXP Card",
            "amount": 4
          }
        ]
      },
      {
        "priceInBricks": 1000,
        "items": [
          {
            "name": "Drone Combat Boost EXP Card",
            "amount": 8
          }
        ]
      },
      {
        "priceInBricks": 2000,
        "items": [
          {
            "name": "Drone Combat Boost EXP Card",
            "amount": 16
          }
        ]
      },
      {
        "priceInBricks": 5000,
        "items": [
          {
            "name": "Drone Combat Boost EXP Card",
            "amount": 40
          }
        ]
      },
      {
        "priceInBricks": 10000,
        "items": [
          {
            "name": "Drone Combat Boost EXP Card",
            "amount": 80
          }
        ]
      }
    ]
  },
  {
    "id": "overlord-training-special-offer",
    "name": "Overlord Training Special Offer Pack",
    "availability": "One-time",
    "availabilityType": "one-time",
    "tiers": [
      {
        "priceInBricks": 500,
        "items": [
          {
            "name": "Training Certificate",
            "amount": 30
          },
          {
            "name": "Training Guidebook",
            "amount": 4000
          }
        ]
      },
      {
        "priceInBricks": 1000,
        "items": [
          {
            "name": "Training Certificate",
            "amount": 50
          },
          {
            "name": "Training Guidebook",
            "amount": 8000
          }
        ]
      },
      {
        "priceInBricks": 2000,
        "items": [
          {
            "name": "Training Certificate",
            "amount": 100
          },
          {
            "name": "Training Guidebook",
            "amount": 16000
          }
        ]
      },
      {
        "priceInBricks": 5000,
        "items": [
          {
            "name": "Training Certificate",
            "amount": 200
          },
          {
            "name": "Training Guidebook",
            "amount": 32000
          }
        ]
      },
      {
        "priceInBricks": 10000,
        "items": [
          {
            "name": "Training Certificate",
            "amount": 400
          },
          {
            "name": "Training Guidebook",
            "amount": 64000
          }
        ]
      }
    ]
  },
  {
    "id": "overlord-promotion-special-offer",
    "name": "Overlord Promotion Special Offer Pack",
    "availability": "One-time",
    "availabilityType": "one-time",
    "tiers": [
      {
        "priceInBricks": 500,
        "items": [
          {
            "name": "Gorilla Overlord Shard",
            "amount": 10
          },
          {
            "name": "Overlord Skill Badge",
            "amount": 500
          }
        ]
      },
      {
        "priceInBricks": 1000,
        "items": [
          {
            "name": "Gorilla Overlord Shard",
            "amount": 20
          },
          {
            "name": "Overlord Skill Badge",
            "amount": 1000
          }
        ]
      },
      {
        "priceInBricks": 2000,
        "items": [
          {
            "name": "Gorilla Overlord Shard",
            "amount": 40
          },
          {
            "name": "Overlord Skill Badge",
            "amount": 2000
          }
        ]
      },
      {
        "priceInBricks": 5000,
        "items": [
          {
            "name": "Gorilla Overlord Shard",
            "amount": 80
          },
          {
            "name": "Overlord Skill Badge",
            "amount": 5000
          }
        ]
      },
      {
        "priceInBricks": 10000,
        "items": [
          {
            "name": "Gorilla Overlord Shard",
            "amount": 160
          },
          {
            "name": "Overlord Skill Badge",
            "amount": 10000
          }
        ]
      }
    ]
  }
];

// ─── FLAT / MISCELLANEOUS PACKS ──────────────────────────────────────────────

export const FLAT_PACKS: FlatPack[] = [
  {
    "id": "mega-express-contract-train",
    "name": "Mega Express Contract (Train)",
    "availability": 2,
    "priceInBricks": 10000,
    "items": [
      {
        "name": "Valor Badge",
        "amount": 1000
      },
      {
        "name": "5m Speed-up",
        "amount": 600
      },
      {
        "name": "Food Chest (UR)",
        "amount": 10
      },
      {
        "name": "Iron Chest (UR)",
        "amount": 10
      },
      {
        "name": "Coin Chest (UR)",
        "amount": 40
      }
    ]
  }
];

// ─── BATTLE PASSES ────────────────────────────────────────────────────────────

export const BATTLE_PASSES: BattlePass[] = [
  {
    "id": "hero-growth-battle-pass",
    "name": "Hero Growth Battle Pass",
    "rotation": "event",
    "tiers": [
      {
        "name": "Advanced Pass",
        "priceInBricks": 500,
        "items": [
          {
            "name": "Hero Shard and Exclusive Weapon Choice Chest",
            "amount": 20
          },
          {
            "name": "Hero Recruitment Ticket",
            "amount": 15
          },
          {
            "name": "Skill Medal",
            "amount": 3000
          }
        ]
      },
      {
        "name": "Premium Pass",
        "priceInBricks": 2000,
        "items": [
          {
            "name": "Hero Shard and Exclusive Weapon Choice Chest",
            "amount": 55
          },
          {
            "name": "Skill Medal Lucky Chest",
            "amount": 1
          },
          {
            "name": "Hero Recruitment Ticket",
            "amount": 30
          },
          {
            "name": "Skill Medal",
            "amount": 7000
          }
        ]
      }
    ]
  },
  {
    "id": "drone-training-pass",
    "name": "Drone Training Pass",
    "rotation": "event",
    "tiers": [
      {
        "name": "Advanced Pass",
        "priceInBricks": 500,
        "items": [
          {
            "name": "Skill Chip Chest (SSR)",
            "amount": 3
          },
          {
            "name": "Premium Chip Material",
            "amount": 300
          },
          {
            "name": "Basic Chip Material",
            "amount": 1100
          },
          {
            "name": "Skill Chip Chest (SR)",
            "amount": 8
          },
          {
            "name": "Drone Combat Boost EXP Card",
            "amount": 12
          }
        ]
      },
      {
        "name": "Premium Pass",
        "priceInBricks": 2000,
        "items": [
          {
            "name": "Skill Chip Chest (SSR)",
            "amount": 6
          },
          {
            "name": "Premium Chip Material",
            "amount": 800
          },
          {
            "name": "Basic Chip Material",
            "amount": 1600
          },
          {
            "name": "Skill Chip Choice Chest (UR)",
            "amount": 1
          },
          {
            "name": "Drone Combat Boost EXP Card",
            "amount": 19
          }
        ]
      }
    ]
  },
  {
    "id": "overlord-training-battle-pass",
    "name": "Overlord Training Battle Pass",
    "rotation": "event",
    "tiers": [
      {
        "name": "Advanced Pass",
        "priceInBricks": 500,
        "items": [
          {
            "name": "Bond Badge",
            "amount": 3
          },
          {
            "name": "Training Certificate",
            "amount": 50
          },
          {
            "name": "Training Guidebook",
            "amount": 15000
          },
          {
            "name": "Training Guidebook Chest",
            "amount": 60
          }
        ]
      },
      {
        "name": "Premium Pass",
        "priceInBricks": 2000,
        "items": [
          {
            "name": "Bond Badge",
            "amount": 9
          },
          {
            "name": "Training Certificate",
            "amount": 120
          },
          {
            "name": "Training Guidebook Chest",
            "amount": 600
          }
        ]
      }
    ]
  },
  {
    "id": "special-training-pass",
    "name": "Special Training Pass",
    "rotation": "event",
    "tiers": [
      {
        "name": "Advanced Pass",
        "priceInBricks": 500,
        "items": [
          {
            "name": "Dielectric Ceramic",
            "amount": 130
          },
          {
            "name": "Resource Choice Chest (SSR)",
            "amount": 30
          },
          {
            "name": "Upgrade Ore",
            "amount": 12000
          }
        ]
      },
      {
        "name": "Premium Pass",
        "priceInBricks": 2000,
        "items": [
          {
            "name": "Dielectric Ceramic",
            "amount": 300
          },
          {
            "name": "Resource Choice Chest (SSR)",
            "amount": 75
          },
          {
            "name": "Upgrade Ore",
            "amount": 37500
          }
        ]
      }
    ]
  },
  {
    "id": "overlord-growth-handbook",
    "name": "Overlord Growth Handbook",
    "rotation": "event",
    "_note": "Appears approximately every 2 months and runs for 30 days. Single-tier pass.",
    "tiers": [
      {
        "name": "Pass",
        "priceInBricks": 2500,
        "items": [
          {
            "name": "Overlord Skill Badge 10K",
            "amount": 1
          },
          {
            "name": "Gorilla Overlord Shard",
            "amount": 130
          },
          {
            "name": "Overlord Skill Badge",
            "amount": 11000
          }
        ]
      }
    ]
  },
  {
    "id": "custom-weekly-pass",
    "name": "Custom Weekly Pass",
    "rotation": "weekly",
    "_note": "Choose items from the list each week. The top item (Hero Shard and Exclusive Weapon Choice Chest) is always included.",
    "tiers": [
      {
        "name": "Premium Subscription",
        "priceInBricks": 500,
        "_note": "Includes the top item plus 2 items of your choice.",
        "items": [
          {
            "name": "Hero Shard and Exclusive Weapon Choice Chest",
            "amount": 8,
            "alwaysIncluded": true
          },
          {
            "name": "Universal Exclusive Weapon Shard",
            "amount": 14
          },
          {
            "name": "Drone Parts",
            "amount": 70
          },
          {
            "name": "Dielectric Ceramic",
            "amount": 280
          },
          {
            "name": "Resource Choice Chest (UR)",
            "amount": 14
          },
          {
            "name": "Hero EXP Chest (SSR)",
            "amount": 42
          },
          {
            "name": "Stamina (50)",
            "amount": 14
          },
          {
            "name": "5m Speed-up",
            "amount": 700
          },
          {
            "name": "Upgrade Ore",
            "amount": 7000
          }
        ]
      },
      {
        "name": "Elite Subscription",
        "priceInBricks": 1000,
        "_note": "Includes the top item plus 4 items of your choice.",
        "items": [
          {
            "name": "Hero Shard and Exclusive Weapon Choice Chest",
            "amount": 8,
            "alwaysIncluded": true
          },
          {
            "name": "Universal Exclusive Weapon Shard",
            "amount": 14
          },
          {
            "name": "Drone Parts",
            "amount": 70
          },
          {
            "name": "Dielectric Ceramic",
            "amount": 280
          },
          {
            "name": "Resource Choice Chest (UR)",
            "amount": 14
          },
          {
            "name": "Hero EXP Chest (SSR)",
            "amount": 42
          },
          {
            "name": "Stamina (50)",
            "amount": 14
          },
          {
            "name": "5m Speed-up",
            "amount": 700
          },
          {
            "name": "Upgrade Ore",
            "amount": 7000
          }
        ]
      }
    ]
  },
  {
    "id": "hero-exclusive-weapon-battle-pass",
    "name": "Hero Exclusive Weapon Battle Pass",
    "rotation": "event",
    "_note": "Available in-season only.",
    "tiers": [
      {
        "name": "Pass",
        "priceInBricks": 2000,
        "items": [
          {
            "name": "UR Hero Universal Shard",
            "amount": 30
          },
          {
            "name": "Skill Medal Lucky Chest",
            "amount": 4
          },
          {
            "name": "Resource Choice Chest (UR)",
            "amount": 4
          },
          {
            "name": "Hero Exclusive Weapon Shard",
            "amount": 70
          },
          {
            "name": "Resource Choice Chest (SSR)",
            "amount": 16
          },
          {
            "name": "Skill Medal",
            "amount": 7000
          }
        ]
      }
    ]
  },
  {
    "id": "warriors-battle-pass",
    "name": "Warrior's Battle Pass",
    "rotation": "event",
    "_note": "Available pre-season only.",
    "tiers": [
      {
        "name": "Pass",
        "priceInBricks": 2000,
        "items": [
          {
            "name": "UR Hero Universal Shard",
            "amount": 130
          },
          {
            "name": "Hero Recruitment Ticket",
            "amount": 70
          },
          {
            "name": "Synthetic Resin",
            "amount": 400
          },
          {
            "name": "1h Speed-up",
            "amount": 34
          },
          {
            "name": "Resource Choice Chest (SR)",
            "amount": 435
          },
          {
            "name": "Hero EXP",
            "amount": 1400000
          }
        ]
      }
    ]
  }
];

// ─── BRICK-TO-FIAT CURRENCY TABLE ────────────────────────────────────────────

export const BRICK_CURRENCIES: BrickCurrency[] = undefined;

// ─── SUMMARY FOR BUDDY SYSTEM PROMPT ─────────────────────────────────────────

export function getPackDataSummary(): string {
  const tiered = TIERED_PACKS.map(p => {
    const tierLines = p.tiers.map((t, i) =>
      `  Tier ${i + 1} (${t.priceInBricks} bricks): ${t.items.map(it => `${it.amount}x ${it.name}`).join(', ')}`
    ).join('\n');
    return `[${p.name}] (${p.availability})\n${tierLines}`;
  }).join('\n\n');

  const flat = FLAT_PACKS.map(p =>
    `[${p.name}] (avail: ${p.availability}) ${p.priceInBricks} bricks: ${p.items.map(it => `${it.amount}x ${it.name}`).join(', ')}`
  ).join('\n');

  const passList = BATTLE_PASSES.map(p => {
    const tierLines = p.tiers.map(t =>
      `  ${t.name} (${t.priceInBricks} bricks): ${t.items.map(it => `${it.amount}x ${it.name}`).join(', ')}`
    ).join('\n');
    return `[${p.name}] (${p.rotation})\n${tierLines}`;
  }).join('\n\n');

  return `=== PACK DATA (Powered by cpt-hedge.com) ===

--- TIERED DAILY / ONE-TIME PACKS ---
${tiered}

--- FLAT PACKS ---
${flat}

--- BATTLE PASSES ---
${passList}`;
}
