// @ts-nocheck
// Powered by cpt-hedge.com — data licensed per partnership agreement.
// AUTO-GENERATED by scripts/sync-hedge-data.mjs — DO NOT EDIT BY HAND.
// Source: /api/data/stores/stores
// Re-run sync script after game patches to refresh data.

// lwtStoreItemData.ts
// Raw store item/price/availability data from cpt-hedge.com.
// Strategic advice lives in lwtStoresData.ts — do not merge.

export interface StoreItem {
  name: string; availability: string; rotation: string; amount: number;
  price: number; priceInBricks: number; priceInBricksReduced?: number; tag?: string;
}
export interface StorePack {
  name: string; priceInBricks: number; items: { name: string; amount: number }[];
  availability?: string;
}
export interface StoreMilestone {
  spend: number; rewards: { name: string; amount: number }[];
}
export interface GameStore {
  id: string; name: string; availabilitySchedule: string; currency: string;
  bricksRate?: number; bricksRateReduced?: number;
  items: StoreItem[]; packs?: StorePack[]; milestones?: StoreMilestone[];
}

export const GAME_STORES: GameStore[] = [
  {
    "id": "black-market",
    "name": "Black Market Store",
    "availabilitySchedule": "Available for 4 weeks after each season concludes",
    "currency": "Black Market Cash",
    "bricksRate": 1,
    "bricksRateReduced": 0.625,
    "packs": [
      {
        "name": "Daily Special Black Market Cash Pack",
        "availability": 1,
        "rotation": "daily",
        "item": "Black Market Cash",
        "amount": 800,
        "priceInBricks": 500
      },
      {
        "name": "Daily Premium Black Market Cash Pack",
        "availability": 1,
        "rotation": "daily",
        "item": "Black Market Cash",
        "amount": 1000,
        "priceInBricks": 1000
      },
      {
        "name": "Daily Rare Black Market Cash Pack",
        "availability": 1,
        "rotation": "daily",
        "item": "Black Market Cash",
        "amount": 2000,
        "priceInBricks": 2000
      },
      {
        "name": "Daily Luxury Black Market Cash Pack",
        "availability": 1,
        "rotation": "daily",
        "item": "Black Market Cash",
        "amount": 5000,
        "priceInBricks": 5000
      },
      {
        "name": "Daily Supreme Black Market Cash Pack",
        "availability": 3,
        "rotation": "daily",
        "item": "Black Market Cash",
        "amount": 10000,
        "priceInBricks": 10000
      }
    ],
    "items": [
      {
        "name": "Skill Chip Choice Chest (UR)",
        "availability": "unlimited",
        "rotation": "event",
        "amount": 1,
        "price": 3000,
        "priceInBricks": 3000,
        "priceInBricksReduced": 1875,
        "tag": "discounted"
      },
      {
        "name": "Skill Chip Chest (UR)",
        "availability": "unlimited",
        "rotation": "event",
        "amount": 1,
        "price": 1500,
        "priceInBricks": 1500,
        "priceInBricksReduced": 937.5,
        "tag": "discounted"
      },
      {
        "name": "Decoration",
        "availability": "unlimited",
        "rotation": "event",
        "amount": 1,
        "price": 800,
        "priceInBricks": 800,
        "priceInBricksReduced": 500,
        "tag": "discounted"
      },
      {
        "name": "UR Hero Universal Shard",
        "availability": "unlimited",
        "rotation": "event",
        "amount": 1,
        "price": 60,
        "priceInBricks": 60,
        "priceInBricksReduced": 37.5,
        "tag": "discounted"
      },
      {
        "name": "Hero Exclusive Weapon Shard Choice Chest",
        "availability": "unlimited",
        "rotation": "event",
        "amount": 1,
        "price": 60,
        "priceInBricks": 60,
        "priceInBricksReduced": 37.5,
        "tag": "discounted"
      },
      {
        "name": "Decoration Chest (UR)",
        "availability": "unlimited",
        "rotation": "event",
        "amount": 1,
        "price": 600,
        "priceInBricks": 600,
        "priceInBricksReduced": 375,
        "tag": "discounted"
      },
      {
        "name": "Bond Badge",
        "availability": "unlimited",
        "rotation": "event",
        "amount": 1,
        "price": 500,
        "priceInBricks": 500,
        "priceInBricksReduced": 312.5,
        "tag": "discounted"
      },
      {
        "name": "Armament Core",
        "availability": "unlimited",
        "rotation": "event",
        "amount": 5,
        "price": 150,
        "priceInBricks": 150,
        "priceInBricksReduced": 93.75,
        "tag": "discounted"
      },
      {
        "name": "Iron Chest (UR)",
        "availability": "unlimited",
        "rotation": "event",
        "amount": 5,
        "price": 120,
        "priceInBricks": 120,
        "priceInBricksReduced": 75,
        "tag": "discounted"
      },
      {
        "name": "Food Chest (UR)",
        "availability": "unlimited",
        "rotation": "event",
        "amount": 5,
        "price": 120,
        "priceInBricks": 120,
        "priceInBricksReduced": 75,
        "tag": "discounted"
      },
      {
        "name": "Coin Chest (UR)",
        "availability": "unlimited",
        "rotation": "event",
        "amount": 5,
        "price": 120,
        "priceInBricks": 120,
        "priceInBricksReduced": 75,
        "tag": "discounted"
      },
      {
        "name": "Upgrade Ore Lucky Chest",
        "availability": "unlimited",
        "rotation": "event",
        "amount": 1,
        "price": 200,
        "priceInBricks": 200,
        "priceInBricksReduced": 125,
        "tag": "discounted"
      },
      {
        "name": "Skill Medal Lucky Chest",
        "availability": "unlimited",
        "rotation": "event",
        "amount": 1,
        "price": 150,
        "priceInBricks": 150,
        "priceInBricksReduced": 93.75,
        "tag": "discounted"
      },
      {
        "name": "Gear Blueprint (UR)",
        "availability": "unlimited",
        "rotation": "event",
        "amount": 1,
        "price": 600,
        "priceInBricks": 600,
        "priceInBricksReduced": 375,
        "tag": "discounted"
      },
      {
        "name": "Drone Parts",
        "availability": "unlimited",
        "rotation": "event",
        "amount": 20,
        "price": 400,
        "priceInBricks": 400,
        "priceInBricksReduced": 250,
        "tag": "discounted"
      },
      {
        "name": "Universal Decor Component",
        "availability": "unlimited",
        "rotation": "event",
        "amount": 30,
        "price": 200,
        "priceInBricks": 200,
        "priceInBricksReduced": 125,
        "tag": "discounted"
      },
      {
        "name": "Upgrade Ore",
        "availability": "unlimited",
        "rotation": "event",
        "amount": 800,
        "price": 100,
        "priceInBricks": 100,
        "priceInBricksReduced": 62.5,
        "tag": "discounted"
      },
      {
        "name": "Skill Medal",
        "availability": "unlimited",
        "rotation": "event",
        "amount": 1000,
        "price": 100,
        "priceInBricks": 100,
        "priceInBricksReduced": 62.5,
        "tag": "discounted"
      },
      {
        "name": "Dielectric Ceramic",
        "availability": "unlimited",
        "rotation": "event",
        "amount": 30,
        "price": 100,
        "priceInBricks": 100,
        "priceInBricksReduced": 62.5,
        "tag": "discounted"
      },
      {
        "name": "5m Speed-up",
        "availability": "unlimited",
        "rotation": "event",
        "amount": 12,
        "price": 10,
        "priceInBricks": 10,
        "priceInBricksReduced": 6.25,
        "tag": "discounted"
      },
      {
        "name": "Overlord Skill Badge",
        "availability": "unlimited",
        "rotation": "event",
        "amount": 2000,
        "price": 100,
        "priceInBricks": 100,
        "priceInBricksReduced": 62.5,
        "tag": "discounted"
      },
      {
        "name": "Training Certificate",
        "availability": "unlimited",
        "rotation": "event",
        "amount": 5,
        "price": 100,
        "priceInBricks": 100,
        "priceInBricksReduced": 62.5,
        "tag": "discounted"
      },
      {
        "name": "10k Profession EXP",
        "availability": "unlimited",
        "rotation": "event",
        "amount": 5,
        "price": 250,
        "priceInBricks": 250,
        "priceInBricksReduced": 156.25,
        "tag": "discounted"
      },
      {
        "name": "Gear Blueprint (UR)",
        "availability": "unlimited",
        "rotation": "event",
        "amount": 5,
        "price": 4000,
        "priceInBricks": 4000,
        "priceInBricksReduced": 2500
      },
      {
        "name": "Gorilla Overlord Shard",
        "availability": "unlimited",
        "rotation": "event",
        "amount": 5,
        "price": 400,
        "priceInBricks": 400,
        "priceInBricksReduced": 250
      },
      {
        "name": "Hero Exclusive Weapon Shard Choice Chest",
        "availability": "unlimited",
        "rotation": "event",
        "amount": 5,
        "price": 500,
        "priceInBricks": 500,
        "priceInBricksReduced": 312.5
      },
      {
        "name": "Skill Chip Choice Chest (UR)",
        "availability": "unlimited",
        "rotation": "event",
        "amount": 1,
        "price": 4000,
        "priceInBricks": 4000,
        "priceInBricksReduced": 2500
      },
      {
        "name": "Skill Chip Chest (UR)",
        "availability": "unlimited",
        "rotation": "event",
        "amount": 1,
        "price": 3000,
        "priceInBricks": 3000,
        "priceInBricksReduced": 1875
      },
      {
        "name": "Armament Core",
        "availability": "unlimited",
        "rotation": "event",
        "amount": 5,
        "price": 300,
        "priceInBricks": 300,
        "priceInBricksReduced": 187.5
      },
      {
        "name": "Valor Badge",
        "availability": "unlimited",
        "rotation": "event",
        "amount": 50,
        "price": 500,
        "priceInBricks": 500,
        "priceInBricksReduced": 312.5
      },
      {
        "name": "Decoration Chest (UR)",
        "availability": "unlimited",
        "rotation": "event",
        "amount": 1,
        "price": 1000,
        "priceInBricks": 1000,
        "priceInBricksReduced": 625
      },
      {
        "name": "Drone Parts",
        "availability": "unlimited",
        "rotation": "event",
        "amount": 15,
        "price": 500,
        "priceInBricks": 500,
        "priceInBricksReduced": 312.5
      },
      {
        "name": "Universal Decor Component",
        "availability": "unlimited",
        "rotation": "event",
        "amount": 50,
        "price": 500,
        "priceInBricks": 500,
        "priceInBricksReduced": 312.5
      },
      {
        "name": "Resource Choice Chest (UR)",
        "availability": "unlimited",
        "rotation": "event",
        "amount": 6,
        "price": 500,
        "priceInBricks": 500,
        "priceInBricksReduced": 312.5
      },
      {
        "name": "1h Speed-up",
        "availability": "unlimited",
        "rotation": "event",
        "amount": 30,
        "price": 800,
        "priceInBricks": 800,
        "priceInBricksReduced": 500
      },
      {
        "name": "Upgrade Ore",
        "availability": "unlimited",
        "rotation": "event",
        "amount": 1000,
        "price": 300,
        "priceInBricks": 300,
        "priceInBricksReduced": 187.5
      },
      {
        "name": "Skill Medal",
        "availability": "unlimited",
        "rotation": "event",
        "amount": 1000,
        "price": 200,
        "priceInBricks": 200,
        "priceInBricksReduced": 125
      },
      {
        "name": "Overlord Skill Badge",
        "availability": "unlimited",
        "rotation": "event",
        "amount": 2000,
        "price": 200,
        "priceInBricks": 200,
        "priceInBricksReduced": 125
      },
      {
        "name": "Dielectric Ceramic",
        "availability": "unlimited",
        "rotation": "event",
        "amount": 60,
        "price": 400,
        "priceInBricks": 400,
        "priceInBricksReduced": 250
      },
      {
        "name": "10k Profession EXP",
        "availability": "unlimited",
        "rotation": "event",
        "amount": 10,
        "price": 1000,
        "priceInBricks": 1000,
        "priceInBricksReduced": 625
      }
    ]
  },
  {
    "id": "total-mobilisation",
    "name": "Total Mobilization",
    "availabilitySchedule": "Available for 1 week as part of the Hot Deals rotation (every ~4 weeks)",
    "currency": "Mobilization Coupons",
    "bricksRate": 50,
    "_note": "Coupons can only be bought through packs. Free coupons are awarded alongside purchases at certain milestones so the prices in bricks can be lowered because of the free coupons.",
    "milestones": [
      {
        "name": "Mobilization Coupons",
        "amount": 20,
        "currencyRequired": 20
      },
      {
        "name": "Mobilization Coupons",
        "amount": 40,
        "currencyRequired": 80
      },
      {
        "name": "Mobilization Coupons",
        "amount": 100,
        "currencyRequired": 200
      },
      {
        "name": "Mobilization Coupons",
        "amount": 300,
        "currencyRequired": 600
      },
      {
        "name": "Gear Blueprint (MR)",
        "amount": 10,
        "currencyRequired": 2000
      }
    ],
    "packs": [
      {
        "name": "Daily Sale Pack",
        "availability": 1,
        "rotation": "daily",
        "item": "Mobilization Coupons",
        "amount": 10,
        "priceInBricks": 500
      },
      {
        "name": "Daily Premium Pack",
        "availability": 1,
        "rotation": "daily",
        "item": "Mobilization Coupons",
        "amount": 20,
        "priceInBricks": 1000
      },
      {
        "name": "Daily Rare Pack",
        "availability": 1,
        "rotation": "daily",
        "item": "Mobilization Coupons",
        "amount": 40,
        "priceInBricks": 2000
      },
      {
        "name": "Daily Deluxe Pack",
        "availability": 1,
        "rotation": "daily",
        "item": "Mobilization Coupons",
        "amount": 100,
        "priceInBricks": 5000
      },
      {
        "name": "Daily Supreme Pack",
        "availability": 3,
        "rotation": "daily",
        "item": "Mobilization Coupons",
        "amount": 200,
        "priceInBricks": 10000
      }
    ],
    "items": [
      {
        "name": "UR Hero Universal Shard",
        "availability": 1,
        "rotation": "daily",
        "amount": 10,
        "price": 10,
        "priceInBricks": 500,
        "tag": "value"
      },
      {
        "name": "Hero Exclusive Weapon Shard Choice Chest",
        "availability": 800,
        "rotation": "event",
        "amount": 1,
        "price": 2,
        "priceInBricks": 100,
        "tag": "resale"
      },
      {
        "name": "Hero Choice Chest",
        "availability": 800,
        "rotation": "event",
        "amount": 1,
        "price": 2,
        "priceInBricks": 100,
        "tag": "resale"
      },
      {
        "name": "Gorilla Overlord Shard",
        "availability": 400,
        "rotation": "event",
        "amount": 1,
        "price": 2,
        "priceInBricks": 100,
        "tag": "resale"
      },
      {
        "name": "Overlord Skill Badge",
        "availability": 400,
        "rotation": "event",
        "amount": 150,
        "price": 1,
        "priceInBricks": 50
      },
      {
        "name": "Lv 5 Drone Component Chest",
        "availability": 50,
        "rotation": "event",
        "amount": 1,
        "price": 30,
        "priceInBricks": 1500
      },
      {
        "name": "Hero EXP Chest (UR)",
        "availability": 100,
        "rotation": "event",
        "amount": 1,
        "price": 3,
        "priceInBricks": 150
      },
      {
        "name": "Survivor Recruitment Ticket",
        "availability": 50,
        "rotation": "event",
        "amount": 10,
        "price": 8,
        "priceInBricks": 400
      },
      {
        "name": "Gear Blueprint (UR)",
        "availability": 20,
        "rotation": "event",
        "amount": 1,
        "price": 12,
        "priceInBricks": 600
      },
      {
        "name": "Premium Chip Material",
        "availability": 80,
        "rotation": "event",
        "amount": 100,
        "price": 7,
        "priceInBricks": 350
      },
      {
        "name": "Upgrade Ore",
        "availability": 1000,
        "rotation": "event",
        "amount": 120,
        "price": 1,
        "priceInBricks": 50
      },
      {
        "name": "Skill Medal",
        "availability": 1000,
        "rotation": "event",
        "amount": 150,
        "price": 1,
        "priceInBricks": 50
      },
      {
        "name": "Resource Choice Chest (SSR)",
        "availability": 4000,
        "rotation": "event",
        "amount": 1,
        "price": 1,
        "priceInBricks": 50
      }
    ]
  },
  {
    "id": "glittering-market",
    "name": "Glittering Market",
    "availabilitySchedule": "Available for 1 week as part of the Hot Deals rotation (every ~4 weeks)",
    "currency": "Glittering Coins",
    "bricksRate": 10,
    "bricksRateReduced": 6.25,
    "milestones": [
      {
        "name": "UR Hero Universal Shard",
        "amount": 10,
        "currencyRequired": 100
      },
      {
        "name": "Decoration Chest (UR)",
        "amount": 1,
        "currencyRequired": 400
      },
      {
        "name": "Lv 5 Drone Component Choice Chest",
        "amount": 1,
        "currencyRequired": 1000
      },
      {
        "name": "Drone Parts",
        "amount": 200,
        "currencyRequired": 4000
      },
      {
        "name": "Universal Decor Component",
        "amount": 1000,
        "currencyRequired": 10000
      }
    ],
    "packs": [
      {
        "name": "Daily Mega Sale Glitter Coin Pack",
        "availability": 1,
        "rotation": "daily",
        "item": "Glittering Coins",
        "amount": 60,
        "priceInBricks": 0,
        "tag": "diamonds"
      },
      {
        "name": "Daily Value Glitter Coin Pack",
        "availability": 1,
        "rotation": "daily",
        "item": "Glittering Coins",
        "amount": 80,
        "priceInBricks": 500
      },
      {
        "name": "Daily Special Glitter Coin Pack",
        "availability": 10,
        "rotation": "daily",
        "item": "Glittering Coins",
        "amount": 100,
        "priceInBricks": 1000
      },
      {
        "name": "Daily Premium Glitter Coin Pack",
        "availability": 10,
        "rotation": "daily",
        "item": "Glittering Coins",
        "amount": 200,
        "priceInBricks": 2000
      },
      {
        "name": "Daily Luxury Glitter Coin Pack",
        "availability": 10,
        "rotation": "daily",
        "item": "Glittering Coins",
        "amount": 500,
        "priceInBricks": 5000
      },
      {
        "name": "Daily Supreme Glitter Coin Pack",
        "availability": 50,
        "rotation": "daily",
        "item": "Glittering Coins",
        "amount": 1000,
        "priceInBricks": 10000
      }
    ],
    "items": [
      {
        "name": "Hero Choice Chest",
        "availability": 1,
        "rotation": "daily",
        "amount": 10,
        "price": 60,
        "priceInBricks": 600,
        "priceInBricksReduced": 375,
        "tag": "offer"
      },
      {
        "name": "Dielectric Ceramic",
        "availability": 1,
        "rotation": "daily",
        "amount": 100,
        "price": 40,
        "priceInBricks": 400,
        "priceInBricksReduced": 250,
        "tag": "offer"
      },
      {
        "name": "Luxury Choice Chest",
        "availability": 1,
        "rotation": "daily",
        "amount": 1,
        "price": 100,
        "priceInBricks": 1000,
        "priceInBricksReduced": 625,
        "tag": "offer"
      },
      {
        "name": "Armament Core",
        "availability": 100,
        "rotation": "event",
        "amount": 10,
        "price": 40,
        "priceInBricks": 400,
        "priceInBricksReduced": 250
      },
      {
        "name": "Armament Materials",
        "availability": 200,
        "rotation": "event",
        "amount": 10000,
        "price": 10,
        "priceInBricks": 100,
        "priceInBricksReduced": 62.5
      },
      {
        "name": "Gear Blueprint (MR)",
        "availability": 10,
        "rotation": "event",
        "amount": 1,
        "price": 300,
        "priceInBricks": 3000,
        "priceInBricksReduced": 1875,
        "tag": "rare"
      },
      {
        "name": "UR Hero Universal Shard",
        "availability": 20,
        "rotation": "event",
        "amount": 1,
        "price": 240,
        "priceCurrency": "Diamonds",
        "priceInBricks": null,
        "tag": "offer"
      },
      {
        "name": "Iron Chest (SSR)",
        "availability": 50,
        "rotation": "event",
        "amount": 1,
        "price": 60,
        "priceCurrency": "Diamonds",
        "priceInBricks": null,
        "tag": "offer"
      },
      {
        "name": "Food Chest (SSR)",
        "availability": 50,
        "rotation": "event",
        "amount": 1,
        "price": 60,
        "priceCurrency": "Diamonds",
        "priceInBricks": null,
        "tag": "offer"
      },
      {
        "name": "Skill Chip Chest (SSR)",
        "availability": 20,
        "rotation": "event",
        "amount": 1,
        "price": 30,
        "priceInBricks": 300,
        "priceInBricksReduced": 187.5
      },
      {
        "name": "Skill Chip Choice Chest (UR)",
        "availability": 5,
        "rotation": "event",
        "amount": 1,
        "price": 300,
        "priceInBricks": 3000,
        "priceInBricksReduced": 1875
      },
      {
        "name": "Skill Chip Chest (UR)",
        "availability": 20,
        "rotation": "event",
        "amount": 1,
        "price": 250,
        "priceInBricks": 2500,
        "priceInBricksReduced": 1562.5
      },
      {
        "name": "Upgrade Ore",
        "availability": 100,
        "rotation": "event",
        "amount": 10000,
        "price": 250,
        "priceInBricks": 2500,
        "priceInBricksReduced": 1562.5
      },
      {
        "name": "Gear Blueprint (UR)",
        "availability": 150,
        "rotation": "event",
        "amount": 1,
        "price": 60,
        "priceInBricks": 600,
        "priceInBricksReduced": 375
      },
      {
        "name": "Dielectric Ceramic",
        "availability": 200,
        "rotation": "event",
        "amount": 100,
        "price": 60,
        "priceInBricks": 600,
        "priceInBricksReduced": 375
      },
      {
        "name": "Valor Badge",
        "availability": 200,
        "rotation": "event",
        "amount": 100,
        "price": 50,
        "priceInBricks": 500,
        "priceInBricksReduced": 312.5
      },
      {
        "name": "1h Speed-up",
        "availability": 200,
        "rotation": "event",
        "amount": 10,
        "price": 20,
        "priceInBricks": 200,
        "priceInBricksReduced": 125
      },
      {
        "name": "Resource Choice Chest (UR)",
        "availability": 500,
        "rotation": "event",
        "amount": 1,
        "price": 5,
        "priceInBricks": 50,
        "priceInBricksReduced": 31.25
      },
      {
        "name": "Dual Propeller Base",
        "availability": 1,
        "rotation": "event",
        "amount": 1,
        "price": 4000,
        "priceInBricks": 40000,
        "priceInBricksReduced": 25000,
        "tag": "rare"
      },
      {
        "name": "Tower of Victory",
        "availability": 81,
        "rotation": "event",
        "amount": 1,
        "price": 100,
        "priceInBricks": 1000,
        "priceInBricksReduced": 625,
        "tag": "rare"
      },
      {
        "name": "Enchanted Fungus Base",
        "availability": 1,
        "rotation": "event",
        "amount": 1,
        "price": 1500,
        "priceInBricks": 15000,
        "priceInBricksReduced": 9375,
        "tag": "resale"
      },
      {
        "name": "UR Hero Universal Shard",
        "availability": 300,
        "rotation": "event",
        "amount": 1,
        "price": 10,
        "priceInBricks": 100,
        "priceInBricksReduced": 62.5
      },
      {
        "name": "Skill Medal",
        "availability": 100,
        "rotation": "event",
        "amount": 10000,
        "price": 120,
        "priceInBricks": 120,
        "priceInBricksReduced": 75
      },
      {
        "name": "Silver Assault Trooper",
        "availability": 81,
        "rotation": "event",
        "amount": 1,
        "price": 40,
        "priceInBricks": 400,
        "priceInBricksReduced": 250
      }
    ]
  },
  {
    "id": "bounty-hunter",
    "name": "Bounty Hunter Store",
    "availabilitySchedule": "Available for 1 week as part of the Hot Deals rotation (every ~4 weeks)",
    "currency": "Bounty Voucher",
    "bricksRate": 8.333,
    "_note": "Vouchers are obtained from killing Zombies during the event with Bullets. Bullets can be bought through packs. Each day you can get some Bullets for free and with Diamonds. It is also possible to obtain Bounty Vouchers from the Wandering Merchant during the event.",
    "secondaryCurrency": {
      "name": "Bounty Bullet",
      "acquiredWith": "key",
      "secondaryCurrencyRatio": 1,
      "secondaryCurrencyNote": "10 Bullets will give you 10 Vouchers on average, but it's not guaranteed and may differ per event based on your luck."
    },
    "secondaryStore": {
      "name": "Wandering Merchant",
      "note": "A secondary vendor that may appear during the event. Sells Bounty Vouchers directly for Bricks - no Bullets needed.",
      "packs": [
        {
          "name": "Wandering Merchant Small Pack",
          "availability": "unlimited",
          "rotation": "event",
          "item": "Bounty Voucher",
          "amount": 120,
          "priceInBricks": 1000
        },
        {
          "name": "Wandering Merchant Large Pack",
          "availability": "unlimited",
          "rotation": "event",
          "item": "Bounty Voucher",
          "amount": 600,
          "priceInBricks": 5000
        }
      ]
    },
    "milestones": [
      {
        "name": "Luxury Choice Chest",
        "amount": 1,
        "currencyRequired": 300
      },
      {
        "name": "Decoration Chest (UR)",
        "amount": 2,
        "currencyRequired": 1000
      },
      {
        "name": "Luxury Choice Chest",
        "amount": 3,
        "currencyRequired": 1800
      },
      {
        "name": "Decoration Chest (UR)",
        "amount": 4,
        "currencyRequired": 3000
      },
      {
        "name": "Luxury Choice Chest",
        "amount": 5,
        "currencyRequired": 5000
      }
    ],
    "packs": [
      {
        "name": "Daily Free Bounty Bullet Pack",
        "availability": 2,
        "rotation": "daily",
        "item": "Bounty Bullet",
        "amount": 10,
        "priceInBricks": 0,
        "tag": "free"
      },
      {
        "name": "Daily Mega Sale Bounty Bullet",
        "availability": 4,
        "rotation": "daily",
        "item": "Bounty Bullet",
        "amount": 20,
        "priceInBricks": 0,
        "tag": "diamonds"
      },
      {
        "name": "Daily Value Bounty Bullet Pack",
        "availability": 1,
        "rotation": "daily",
        "item": "Bounty Bullet",
        "amount": 80,
        "priceInBricks": 500
      },
      {
        "name": "Daily Special Bounty Bullet Pack",
        "availability": 1,
        "rotation": "daily",
        "item": "Bounty Bullet",
        "amount": 100,
        "priceInBricks": 1000
      },
      {
        "name": "Daily Premium Bounty Bullet Pack",
        "availability": 1,
        "rotation": "daily",
        "item": "Bounty Bullet",
        "amount": 200,
        "priceInBricks": 2000
      },
      {
        "name": "Daily Luxury Bounty Bullet Pack",
        "availability": 1,
        "rotation": "daily",
        "item": "Bounty Bullet",
        "amount": 500,
        "priceInBricks": 5000
      },
      {
        "name": "Daily Supreme Bounty Bullet Pack",
        "availability": 1,
        "rotation": "daily",
        "item": "Bounty Bullet",
        "amount": 1000,
        "priceInBricks": 10000
      }
    ],
    "items": [
      {
        "name": "Lv 5 Drone Component Chest",
        "availability": 1,
        "rotation": "daily",
        "amount": 1,
        "price": 80,
        "priceInBricks": 666.667,
        "tag": "must-buy"
      },
      {
        "name": "Bond Badge",
        "availability": 5,
        "rotation": "event",
        "amount": 10,
        "price": 450,
        "priceInBricks": 3750,
        "tag": "must-buy"
      },
      {
        "name": "Training Certificate",
        "availability": 100,
        "rotation": "event",
        "amount": 10,
        "price": 20,
        "priceInBricks": 166.67,
        "tag": "offer"
      },
      {
        "name": "Drone Parts",
        "availability": 200,
        "rotation": "event",
        "amount": 10,
        "price": 22,
        "priceInBricks": 183.33,
        "tag": "offer"
      },
      {
        "name": "Lv 5 Drone Component Choice Chest",
        "availability": 20,
        "rotation": "event",
        "amount": 1,
        "price": 220,
        "priceInBricks": 1833.333,
        "tag": "offer"
      },
      {
        "name": "Training Guidebook",
        "availability": 300,
        "rotation": "event",
        "amount": 1000,
        "price": 3,
        "priceInBricks": 25,
        "tag": "offer"
      },
      {
        "name": "Valor Badge",
        "availability": 100,
        "rotation": "event",
        "amount": 100,
        "price": 50,
        "priceInBricks": 416.7
      },
      {
        "name": "Resource Choice Chest (UR)",
        "availability": 100,
        "rotation": "event",
        "amount": 10,
        "price": 50,
        "priceInBricks": 41.667
      },
      {
        "name": "1h Speed-up",
        "availability": 50,
        "rotation": "event",
        "amount": 10,
        "price": 20,
        "priceInBricks": 166.67
      },
      {
        "name": "Decoration Chest (UR)",
        "availability": 30,
        "rotation": "event",
        "amount": 1,
        "price": 100,
        "priceInBricks": 833.333
      },
      {
        "name": "Drone Parts",
        "availability": 400,
        "rotation": "event",
        "amount": 10,
        "price": 32,
        "priceInBricks": 266.67
      },
      {
        "name": "Battle Data 10K",
        "availability": 400,
        "rotation": "event",
        "amount": 10,
        "price": 20,
        "priceInBricks": 166.67
      },
      {
        "name": "UR Hero Universal Shard",
        "availability": 50,
        "rotation": "event",
        "amount": 10,
        "price": 80,
        "priceInBricks": 666.67
      },
      {
        "name": "Skill Medal",
        "availability": 200,
        "rotation": "event",
        "amount": 1000,
        "price": 15,
        "priceInBricks": 125
      }
    ]
  },
  {
    "id": "bullseye-loot",
    "name": "Bullseye Loot",
    "availabilitySchedule": "Available for 1 week as part of the Hot Deals rotation (every ~4 weeks)",
    "currency": "Ammo",
    "bricksRate": null,
    "_note": "Ammo packs are purchased directly with Bricks. Milestones are based on levels reached, not currency spent.",
    "milestoneType": "level",
    "packs": [
      {
        "name": "Daily Sale Ammo Pack",
        "availability": 1,
        "rotation": "daily",
        "item": "Ammo",
        "amount": 10,
        "priceInBricks": 500
      },
      {
        "name": "Daily Ammo Pack (R)",
        "availability": 1,
        "rotation": "daily",
        "item": "Ammo",
        "amount": 12,
        "priceInBricks": 1000
      },
      {
        "name": "Daily Ammo Pack (SR)",
        "availability": 1,
        "rotation": "daily",
        "item": "Ammo",
        "amount": 24,
        "priceInBricks": 2000
      },
      {
        "name": "Daily Ammo Pack (SSR)",
        "availability": 1,
        "rotation": "daily",
        "item": "Ammo",
        "amount": 60,
        "priceInBricks": 5000
      },
      {
        "name": "Daily Ammo Pack (UR)",
        "availability": 5,
        "rotation": "daily",
        "item": "Ammo",
        "amount": 120,
        "priceInBricks": 10000
      }
    ],
    "milestones": [
      {
        "name": "Upgrade Ore",
        "amount": 2000,
        "level": 5
      },
      {
        "name": "Upgrade Ore",
        "amount": 4000,
        "level": 10
      },
      {
        "name": "Upgrade Ore Lucky Chest",
        "amount": 8,
        "level": 20
      },
      {
        "name": "Gear Boost Choice Chest",
        "amount": 5,
        "level": 30
      },
      {
        "name": "Gear Boost Choice Chest",
        "amount": 5,
        "level": 40
      },
      {
        "name": "Gear Boost Choice Chest",
        "amount": 10,
        "level": 60
      },
      {
        "name": "Gear Boost Choice Chest",
        "amount": 10,
        "level": 80
      },
      {
        "name": "Gear Blueprint (MR)",
        "amount": 10,
        "level": 100
      }
    ]
  },
  {
    "id": "mall",
    "name": "Mall",
    "currency": null,
    "_note": "The Mall allows you to purchase items directly. There are various rotations for the items available in the Mall, including daily sales, weekly deals, and special packs.",
    "bricksRate": null,
    "packs": [
      {
        "name": "Exclusive Weapon Shard (2x)",
        "group": "Daily Sale",
        "availability": 1,
        "rotation": "daily",
        "items": [
          {
            "item": "Universal Exclusive Weapon Shard",
            "amount": 2
          }
        ],
        "priceInBricks": 100,
        "_note": "1 daily per hero"
      },
      {
        "name": "Exclusive Weapon Shard (3x)",
        "group": "Daily Sale",
        "availability": 1,
        "rotation": "daily",
        "items": [
          {
            "item": "Universal Exclusive Weapon Shard",
            "amount": 3
          }
        ],
        "priceInBricks": 200,
        "_note": "1 daily per hero"
      },
      {
        "name": "Exclusive Weapon Shard (5x)",
        "group": "Daily Sale",
        "availability": 1,
        "rotation": "daily",
        "items": [
          {
            "item": "Universal Exclusive Weapon Shard",
            "amount": 5
          }
        ],
        "priceInBricks": 400,
        "_note": "1 daily per hero"
      },
      {
        "name": "Exclusive Weapon Shard (10x)",
        "group": "Daily Sale - Take All",
        "availability": 1,
        "rotation": "daily",
        "items": [
          {
            "item": "Universal Exclusive Weapon Shard",
            "amount": 10
          }
        ],
        "priceInBricks": 500,
        "_note": "1 daily per hero"
      },
      {
        "name": "UR Hero Shard (2x)",
        "group": "Daily Sale",
        "availability": 1,
        "rotation": "daily",
        "items": [
          {
            "item": "UR Hero Universal Shard",
            "amount": 2
          }
        ],
        "priceInBricks": 100,
        "_note": "1 daily per hero"
      },
      {
        "name": "UR Hero Shard (3x)",
        "group": "Daily Sale",
        "availability": 1,
        "rotation": "daily",
        "items": [
          {
            "item": "UR Hero Universal Shard",
            "amount": 3
          }
        ],
        "priceInBricks": 200,
        "_note": "1 daily per hero"
      },
      {
        "name": "UR Hero Shard (5x)",
        "group": "Daily Sale",
        "availability": 1,
        "rotation": "daily",
        "items": [
          {
            "item": "UR Hero Universal Shard",
            "amount": 5
          }
        ],
        "priceInBricks": 400,
        "_note": "1 daily per hero"
      },
      {
        "name": "UR Hero Shard (10x)",
        "group": "Daily Sale - Take All",
        "availability": 1,
        "rotation": "daily",
        "items": [
          {
            "item": "UR Hero Universal Shard",
            "amount": 10
          }
        ],
        "priceInBricks": 500,
        "_note": "1 daily per hero"
      },
      {
        "name": "Overlord Training Pack",
        "group": "Daily Must-buy",
        "availability": 1,
        "rotation": "daily",
        "items": [
          {
            "item": "Training Certificate",
            "amount": 30
          }
        ],
        "priceInBricks": 500
      },
      {
        "name": "Daily Drone Skill Chip",
        "group": "Daily Must-buy",
        "availability": 1,
        "rotation": "daily",
        "items": [
          {
            "item": "Skill Chip Chest (SSR)",
            "amount": 1
          }
        ],
        "priceInBricks": 500
      },
      {
        "name": "Valor Badge",
        "group": "Daily Must-buy",
        "availability": 1,
        "rotation": "daily",
        "items": [
          {
            "item": "Valor Badge",
            "amount": 50
          }
        ],
        "priceInBricks": 500
      },
      {
        "name": "Drone Parts",
        "group": "Daily Must-buy",
        "availability": 1,
        "rotation": "daily",
        "items": [
          {
            "item": "Drone Parts",
            "amount": 20
          }
        ],
        "priceInBricks": 500
      },
      {
        "name": "Decoration Collection",
        "group": "Daily Must-buy",
        "availability": 1,
        "rotation": "daily",
        "items": [
          {
            "item": "Universal Decor Component Lucky Chest",
            "amount": 1
          }
        ],
        "priceInBricks": 500
      },
      {
        "name": "Universal Speed-up Pack",
        "group": "Daily Must-buy",
        "availability": 1,
        "rotation": "daily",
        "items": [
          {
            "item": "5m Speed-up",
            "amount": 180
          }
        ],
        "priceInBricks": 500
      },
      {
        "name": "Value Food Pack",
        "group": "Daily Must-buy",
        "availability": 1,
        "rotation": "daily",
        "items": [
          {
            "item": "Food Chest (UR)",
            "amount": 8
          }
        ],
        "priceInBricks": 500
      },
      {
        "name": "Value Iron Pack",
        "group": "Daily Must-buy",
        "availability": 1,
        "rotation": "daily",
        "items": [
          {
            "item": "Iron Chest (UR)",
            "amount": 8
          }
        ],
        "priceInBricks": 500
      },
      {
        "name": "Value Coin Pack",
        "group": "Daily Must-buy",
        "availability": 1,
        "rotation": "daily",
        "items": [
          {
            "item": "Coin Chest (UR)",
            "amount": 8
          }
        ],
        "priceInBricks": 500
      },
      {
        "name": "Oil Special Offer Pack",
        "group": "Weekly Deal",
        "availability": 5,
        "rotation": "weekly",
        "items": [
          {
            "item": "10.0K Oil",
            "amount": 40
          }
        ],
        "priceInBricks": 2000
      },
      {
        "name": "Valor Badge",
        "group": "Weekly Deal",
        "availability": 5,
        "rotation": "weekly",
        "items": [
          {
            "item": "Valor Badge",
            "amount": 1000
          },
          {
            "item": "5m Research Speed-up",
            "amount": 1200
          }
        ],
        "priceInBricks": 10000
      },
      {
        "name": "Armament Research Special",
        "group": "Weekly Deal",
        "availability": 4,
        "rotation": "weekly",
        "items": [
          {
            "item": "Armament Core",
            "amount": 100
          },
          {
            "item": "Armament Materials",
            "amount": 180000
          }
        ],
        "priceInBricks": 5000
      },
      {
        "name": "Profession EXP Pack",
        "group": "Weekly Deal",
        "availability": 5,
        "rotation": "weekly",
        "items": [
          {
            "item": "10k Profession EXP",
            "amount": 10
          }
        ],
        "priceInBricks": 1000
      },
      {
        "name": "Training Certificate Pack",
        "group": "Weekly Deal",
        "availability": 4,
        "rotation": "weekly",
        "items": [
          {
            "item": "Training Certificate",
            "amount": 180
          },
          {
            "item": "Training Guidebook",
            "amount": 30000
          }
        ],
        "priceInBricks": 5000
      },
      {
        "name": "Base Upgrade",
        "group": "Weekly Deal",
        "availability": 5,
        "rotation": "weekly",
        "items": [
          {
            "item": "5m Speed-up",
            "amount": 180
          }
        ],
        "priceInBricks": 2000
      },
      {
        "name": "Bond Badge Pack",
        "group": "Weekly Deal",
        "availability": 1,
        "rotation": "weekly",
        "items": [
          {
            "item": "Bond Badge",
            "amount": 10
          }
        ],
        "priceInBricks": 5000
      },
      {
        "name": "Universal Overlord Shard Pack",
        "group": "Weekly Deal",
        "availability": 2,
        "rotation": "weekly",
        "items": [
          {
            "item": "Universal Overlord Shard",
            "amount": 40
          },
          {
            "item": "Overlord Skill Badge",
            "amount": 8000
          }
        ],
        "priceInBricks": 5000
      },
      {
        "name": "Drone Component",
        "group": "Weekly Deal",
        "availability": 6,
        "rotation": "weekly",
        "items": [
          {
            "item": "Lv 5 Drone Component Choice Chest",
            "amount": 1
          },
          {
            "item": "Lv 5 Drone Component Chest",
            "amount": 1
          },
          {
            "item": "Lv 3 Drone Component Chest",
            "amount": 3
          }
        ],
        "priceInBricks": 5000
      },
      {
        "name": "Drone Parts",
        "group": "Weekly Deal",
        "availability": 6,
        "rotation": "weekly",
        "items": [
          {
            "item": "Drone Parts",
            "amount": 150
          },
          {
            "item": "Battle Data 10K",
            "amount": 40
          }
        ],
        "priceInBricks": 5000
      },
      {
        "name": "Weekly Drone Skill Chip",
        "group": "Weekly Deal",
        "availability": 10,
        "rotation": "weekly",
        "items": [
          {
            "item": "Skill Chip Chest (UR)",
            "amount": 1
          },
          {
            "item": "Skill Chip Chest (SSR)",
            "amount": 4
          },
          {
            "item": "Skill Chip Chest (R)",
            "amount": 20
          }
        ],
        "priceInBricks": 5000
      },
      {
        "name": "Weekly Decoration Collection",
        "group": "Weekly Deal",
        "availability": 7,
        "rotation": "weekly",
        "items": [
          {
            "item": "Universal Decor Component",
            "amount": 1100
          }
        ],
        "priceInBricks": 10000
      },
      {
        "name": "Stamina Special Offer Pack",
        "group": "Weekly Deal",
        "availability": 5,
        "rotation": "weekly",
        "items": [
          {
            "item": "Stamina (50)",
            "amount": 10
          },
          {
            "item": "5m Speed-up",
            "amount": 200
          }
        ],
        "priceInBricks": 1000
      },
      {
        "name": "Universal Exclusive Weapon Shard",
        "group": "Weekly Deal",
        "availability": 2,
        "rotation": "weekly",
        "items": [
          {
            "item": "Universal Exclusive Weapon Shard",
            "amount": 80
          }
        ],
        "priceInBricks": 10000
      },
      {
        "name": "Take All Weekly Pass",
        "group": "Weekly Pass",
        "availability": 1,
        "rotation": "weekly",
        "items": [
          {
            "item": "Armament Core",
            "amount": 84
          },
          {
            "item": "Drone Parts",
            "amount": 105
          },
          {
            "item": "Lv 4 Drone Component Chest",
            "amount": 7
          },
          {
            "item": "Hero EXP Chest (UR)",
            "amount": 21
          },
          {
            "item": "Coin Chest (UR)",
            "amount": 21
          }
        ],
        "priceInBricks": 2000
      },
      {
        "name": "(S4) Armament Core Weekly Pass",
        "group": "Weekly Pass",
        "availability": 1,
        "rotation": "weekly",
        "items": [
          {
            "item": "Armament Core",
            "amount": 84
          }
        ],
        "priceInBricks": 500
      },
      {
        "name": "(S1) Drone Parts Weekly Pass",
        "group": "Weekly Pass",
        "availability": 1,
        "rotation": "weekly",
        "items": [
          {
            "item": "Drone Parts",
            "amount": 105
          }
        ],
        "priceInBricks": 500
      },
      {
        "name": "(S2) Drone Components Weekly Pass",
        "group": "Weekly Pass",
        "availability": 1,
        "rotation": "weekly",
        "items": [
          {
            "item": "Lv 4 Drone Component Chest",
            "amount": 7
          }
        ],
        "priceInBricks": 500
      },
      {
        "name": "EXP Weekly Pass",
        "group": "Weekly Pass",
        "availability": 1,
        "rotation": "weekly",
        "items": [
          {
            "item": "Hero EXP Chest (UR)",
            "amount": 21
          }
        ],
        "priceInBricks": 500
      },
      {
        "name": "Coin Weekly Pass",
        "group": "Weekly Pass",
        "availability": 1,
        "rotation": "weekly",
        "items": [
          {
            "item": "Coin Chest (UR)",
            "amount": 21
          }
        ],
        "priceInBricks": 500
      },
      {
        "name": "Fast Growth Pack",
        "group": "Pack Store",
        "availability": 1,
        "rotation": "daily",
        "items": [
          {
            "item": "5m Speed-up",
            "amount": 60
          },
          {
            "item": "Iron Chest (UR)",
            "amount": 2
          },
          {
            "item": "Food Chest (UR)",
            "amount": 2
          },
          {
            "item": "Coin Chest (UR)",
            "amount": 2
          }
        ],
        "priceInBricks": 500
      },
      {
        "name": "Overlord Training Pack",
        "group": "Pack Store",
        "availability": 1,
        "rotation": "daily",
        "items": [
          {
            "item": "Training Guidebook",
            "amount": 4000
          }
        ],
        "priceInBricks": 500
      },
      {
        "name": "Drone Parts Pack",
        "group": "Pack Store",
        "availability": 1,
        "rotation": "daily",
        "items": [
          {
            "item": "Drone Parts",
            "amount": 10
          },
          {
            "item": "Battle Data 10K",
            "amount": 3
          }
        ],
        "priceInBricks": 500
      },
      {
        "name": "Drone Component Pack",
        "group": "Pack Store",
        "availability": 1,
        "rotation": "daily",
        "items": [
          {
            "item": "Lv 3 Drone Component Chest",
            "amount": 2
          },
          {
            "item": "Coin Chest (SSR)",
            "amount": 2
          }
        ],
        "priceInBricks": 500
      },
      {
        "name": "Hero Growth Pack",
        "group": "Pack Store",
        "availability": 1,
        "rotation": "daily",
        "items": [
          {
            "item": "Hero Recruitment Ticket",
            "amount": 5
          },
          {
            "item": "Hero EXP Chest (SR)",
            "amount": 4
          },
          {
            "item": "Skill Medal",
            "amount": 750
          }
        ],
        "priceInBricks": 500
      },
      {
        "name": "Tech Boost Pack",
        "group": "Pack Store",
        "availability": 1,
        "rotation": "daily",
        "items": [
          {
            "item": "5m Research Speed-up",
            "amount": 60
          },
          {
            "item": "Iron Chest (UR)",
            "amount": 1
          },
          {
            "item": "Food Chest (UR)",
            "amount": 1
          },
          {
            "item": "Coin Chest (UR)",
            "amount": 4
          }
        ],
        "priceInBricks": 500
      },
      {
        "name": "Decoration Collection",
        "group": "Pack Store",
        "availability": 1,
        "rotation": "daily",
        "items": [
          {
            "item": "Universal Decor Component",
            "amount": 900
          }
        ],
        "priceInBricks": 10000
      },
      {
        "name": "Gear Progression Pack",
        "group": "Pack Store",
        "availability": 1,
        "rotation": "daily",
        "items": [
          {
            "item": "Upgrade Ore",
            "amount": 1000
          },
          {
            "item": "Synthetic Resin",
            "amount": 30
          },
          {
            "item": "Coin Chest (SSR)",
            "amount": 1
          }
        ],
        "priceInBricks": 500
      },
      {
        "name": "Military Training Pack",
        "group": "Pack Store",
        "availability": 1,
        "rotation": "daily",
        "items": [
          {
            "item": "5m Training Speed-up",
            "amount": 60
          },
          {
            "item": "Iron Chest (UR)",
            "amount": 2
          },
          {
            "item": "Food Chest (UR)",
            "amount": 2
          },
          {
            "item": "Coin Chest (UR)",
            "amount": 2
          }
        ],
        "priceInBricks": 500
      },
      {
        "name": "Moonlight Pack",
        "group": "Pack Store",
        "availability": 1,
        "rotation": "2 weeks",
        "items": [
          {
            "item": "UR Hero Universal Shard",
            "amount": 10
          },
          {
            "item": "Resource Choice Chest (SSR)",
            "amount": 10
          },
          {
            "item": "Upgrade Ore",
            "amount": 1000
          }
        ],
        "priceInBricks": 500
      },
      {
        "name": "Survivor Recruit Pack",
        "group": "Pack Store",
        "availability": 1,
        "rotation": "daily",
        "items": [
          {
            "item": "Survivor Recruitment Ticket",
            "amount": 10
          }
        ],
        "priceInBricks": 500
      }
    ],
    "items": []
  },
  {
    "id": "vip-store",
    "name": "VIP Store",
    "availabilitySchedule": "Restocks weekly on Monday",
    "currency": "Diamonds",
    "bricksRate": null,
    "bricksConversionNote": "Diamonds are generally earned through gameplay and pack purchases (approx. 1 diamond per brick spent).",
    "packs": [],
    "items": [
      {
        "name": "Food Chest (SR)",
        "availability": 100,
        "rotation": "weekly",
        "amount": 1,
        "price": 40
      },
      {
        "name": "Iron Chest (SR)",
        "availability": 100,
        "rotation": "weekly",
        "amount": 1,
        "price": 40
      },
      {
        "name": "Coin Chest (SR)",
        "availability": 100,
        "rotation": "weekly",
        "amount": 1,
        "price": 40
      },
      {
        "name": "Armament Materials",
        "availability": 6,
        "rotation": "weekly",
        "amount": 5000,
        "price": 200
      },
      {
        "name": "Armament Core",
        "availability": 5,
        "rotation": "weekly",
        "amount": 1,
        "price": 100
      },
      {
        "name": "Bond Badge",
        "availability": 1,
        "rotation": "weekly",
        "amount": 1,
        "price": 3000
      },
      {
        "name": "Training Guidebook",
        "availability": 6000,
        "rotation": "weekly",
        "amount": 1,
        "price": 1
      },
      {
        "name": "Universal Decor Component",
        "availability": 50,
        "rotation": "weekly",
        "amount": 1,
        "price": 100
      },
      {
        "name": "Stamina (50)",
        "availability": 5,
        "rotation": "weekly",
        "amount": 1,
        "price": 60
      },
      {
        "name": "Superalloy",
        "availability": 100,
        "rotation": "weekly",
        "amount": 1,
        "price": 6
      },
      {
        "name": "Advanced Teleporter",
        "availability": 3,
        "rotation": "weekly",
        "amount": 1,
        "price": 600
      },
      {
        "name": "Drone Parts",
        "availability": 50,
        "rotation": "weekly",
        "amount": 1,
        "price": 400
      },
      {
        "name": "Skill Medal",
        "availability": 2000,
        "rotation": "weekly",
        "amount": 1,
        "price": 4
      },
      {
        "name": "SR Hero Universal Shard",
        "availability": 50,
        "rotation": "weekly",
        "amount": 1,
        "price": 40
      },
      {
        "name": "Hero EXP Chest (SSR)",
        "availability": 50,
        "rotation": "weekly",
        "amount": 1,
        "price": 160
      },
      {
        "name": "5m Speed-up",
        "availability": 200,
        "rotation": "weekly",
        "amount": 1,
        "price": 8
      },
      {
        "name": "Upgrade Ore",
        "availability": 1500,
        "rotation": "weekly",
        "amount": 1,
        "price": 4
      },
      {
        "name": "Skill Chip Chest (SR)",
        "availability": 10,
        "rotation": "weekly",
        "amount": 1,
        "price": 800
      },
      {
        "name": "Synthetic Resin",
        "availability": 100,
        "rotation": "weekly",
        "amount": 1,
        "price": 16
      },
      {
        "name": "Survivor Recruitment Ticket",
        "availability": 50,
        "rotation": "weekly",
        "amount": 1,
        "price": 200
      },
      {
        "name": "Hero EXP Chest (UR)",
        "availability": 20,
        "rotation": "weekly",
        "amount": 1,
        "price": 480
      },
      {
        "name": "1h Speed-up",
        "availability": 60,
        "rotation": "weekly",
        "amount": 1,
        "price": 72
      },
      {
        "name": "SSR Hero Universal Shard",
        "availability": 30,
        "rotation": "weekly",
        "amount": 1,
        "price": 200
      },
      {
        "name": "4h Speed-up",
        "availability": 20,
        "rotation": "weekly",
        "amount": 1,
        "price": 192
      },
      {
        "name": "Dielectric Ceramic",
        "availability": 50,
        "rotation": "weekly",
        "amount": 1,
        "price": 64
      },
      {
        "name": "8h Speed-up",
        "availability": 10,
        "rotation": "weekly",
        "amount": 1,
        "price": 480
      },
      {
        "name": "UR Hero Universal Shard",
        "availability": 10,
        "rotation": "weekly",
        "amount": 1,
        "price": 300
      }
    ]
  },
  {
    "id": "diamond-store",
    "name": "Diamond Store",
    "availabilitySchedule": "Restocks weekly on Monday",
    "currency": "Diamonds",
    "bricksRate": null,
    "bricksConversionNote": "Diamonds are generally earned through gameplay and pack purchases (approx. 1 diamond per brick spent).",
    "packs": [],
    "items": [
      {
        "name": "Hero Recruitment Ticket",
        "availability": "unlimited",
        "rotation": "always",
        "amount": 1,
        "price": 400
      },
      {
        "name": "Survivor Recruitment Ticket",
        "availability": "unlimited",
        "rotation": "always",
        "amount": 1,
        "price": 400
      },
      {
        "name": "50k Iron",
        "availability": "unlimited",
        "rotation": "always",
        "amount": 1,
        "price": 50
      },
      {
        "name": "50k Food",
        "availability": "unlimited",
        "rotation": "always",
        "amount": 1,
        "price": 50
      },
      {
        "name": "18k Coins",
        "availability": "unlimited",
        "rotation": "always",
        "amount": 1,
        "price": 50
      },
      {
        "name": "Trade Contract",
        "availability": "unlimited",
        "rotation": "always",
        "amount": 1,
        "price": 100
      },
      {
        "name": "Advanced Teleporter",
        "availability": "unlimited",
        "rotation": "always",
        "amount": 1,
        "price": 1500
      },
      {
        "name": "Alliance Teleporter",
        "availability": "unlimited",
        "rotation": "always",
        "amount": 1,
        "price": 500
      }
    ]
  },
  {
    "id": "zombie-invasion",
    "name": "Zombie Invasion Store",
    "availabilitySchedule": "Available every 2 weeks as part of the Zombie Invasion event",
    "currency": "Courage Medal",
    "bricksRate": null,
    "bricksConversionNote": "Courage Medals are earned through Zombie Invasion gameplay and cannot be purchased.",
    "packs": [],
    "items": [
      {
        "name": "10.0K Oil",
        "availability": 10,
        "rotation": "event",
        "amount": 1,
        "price": 500,
        "priceInBricks": null
      },
      {
        "name": "Armament Core",
        "availability": 30,
        "rotation": "event",
        "amount": 1,
        "price": 80,
        "priceInBricks": null
      },
      {
        "name": "Universal Exclusive Weapon Shard",
        "availability": 10,
        "rotation": "event",
        "amount": 1,
        "price": 120,
        "priceInBricks": null
      },
      {
        "name": "Hero Recruitment Ticket",
        "availability": 10,
        "rotation": "event",
        "amount": 1,
        "price": 80,
        "priceInBricks": null
      },
      {
        "name": "Survivor Recruitment Ticket",
        "availability": 30,
        "rotation": "event",
        "amount": 1,
        "price": 80,
        "priceInBricks": null
      },
      {
        "name": "Stamina (50)",
        "availability": 3,
        "rotation": "event",
        "amount": 1,
        "price": 10,
        "priceInBricks": null
      },
      {
        "name": "Training Certificate",
        "availability": 20,
        "rotation": "event",
        "amount": 1,
        "price": 50,
        "priceInBricks": null
      },
      {
        "name": "Overlord Supply Chest (SSR)",
        "availability": 30,
        "rotation": "event",
        "amount": 1,
        "price": 100,
        "priceInBricks": null
      },
      {
        "name": "Overlord Skill Badge",
        "availability": 5,
        "rotation": "event",
        "amount": 1000,
        "price": 250,
        "priceInBricks": null
      },
      {
        "name": "Iron Chest (SSR)",
        "availability": 50,
        "rotation": "event",
        "amount": 1,
        "price": 160,
        "priceInBricks": null
      },
      {
        "name": "Food Chest (SSR)",
        "availability": 50,
        "rotation": "event",
        "amount": 1,
        "price": 160,
        "priceInBricks": null
      },
      {
        "name": "Coin Chest (SSR)",
        "availability": 100,
        "rotation": "event",
        "amount": 1,
        "price": 160,
        "priceInBricks": null
      },
      {
        "name": "Coin Chest (UR)",
        "availability": 20,
        "rotation": "event",
        "amount": 1,
        "price": 480,
        "priceInBricks": null
      },
      {
        "name": "Valor Badge",
        "availability": 50,
        "rotation": "event",
        "amount": 10,
        "price": 200,
        "priceInBricks": null
      },
      {
        "name": "Drone Parts",
        "availability": 50,
        "rotation": "event",
        "amount": 1,
        "price": 200,
        "priceInBricks": null
      },
      {
        "name": "Lv 3 Drone Component Chest",
        "availability": 3,
        "rotation": "event",
        "amount": 1,
        "price": 360,
        "priceInBricks": null
      },
      {
        "name": "Skill Chip Chest (SR)",
        "availability": 3,
        "rotation": "event",
        "amount": 1,
        "price": 120,
        "priceInBricks": null
      },
      {
        "name": "Skill Chip Chest (SSR)",
        "availability": 1,
        "rotation": "event",
        "amount": 1,
        "price": 400,
        "priceInBricks": null
      },
      {
        "name": "5m Research Speed-up",
        "availability": 100,
        "rotation": "event",
        "amount": 1,
        "price": 4,
        "priceInBricks": null
      },
      {
        "name": "1h Research Speed-up",
        "availability": 10,
        "rotation": "event",
        "amount": 1,
        "price": 36,
        "priceInBricks": null
      },
      {
        "name": "5m Construction Speed-up",
        "availability": 50,
        "rotation": "event",
        "amount": 1,
        "price": 4,
        "priceInBricks": null
      },
      {
        "name": "Synthetic Resin",
        "availability": 300,
        "rotation": "event",
        "amount": 1,
        "price": 8,
        "priceInBricks": null
      },
      {
        "name": "Upgrade Ore",
        "availability": 100,
        "rotation": "event",
        "amount": 50,
        "price": 100,
        "priceInBricks": null
      }
    ]
  },
  {
    "id": "alliance-store",
    "name": "Alliance Store",
    "availabilitySchedule": "Restocks weekly on Monday",
    "currency": "Alliance Points",
    "bricksRate": null,
    "bricksConversionNote": "Alliance Points are earned through alliance activities.",
    "packs": [],
    "items": [
      {
        "name": "UR Hero Universal Shard",
        "availability": 5,
        "rotation": "weekly",
        "amount": 1,
        "price": 3000
      },
      {
        "name": "Bond Badge",
        "availability": 1,
        "rotation": "weekly",
        "amount": 1,
        "price": 3000
      },
      {
        "name": "Universal Overlord Shard",
        "availability": 5,
        "rotation": "weekly",
        "amount": 1,
        "price": 2000
      },
      {
        "name": "Survivor Recruitment Ticket",
        "availability": 30,
        "rotation": "weekly",
        "amount": 1,
        "price": 2000
      },
      {
        "name": "Armament Materials",
        "availability": 10,
        "rotation": "weekly",
        "amount": 2000,
        "price": 1000
      },
      {
        "name": "Violet Shard",
        "availability": 30,
        "rotation": "weekly",
        "amount": 1,
        "price": 1000
      },
      {
        "name": "Sarah Shard",
        "availability": 30,
        "rotation": "weekly",
        "amount": 1,
        "price": 1000
      },
      {
        "name": "Scarlett Shard",
        "availability": 30,
        "rotation": "weekly",
        "amount": 1,
        "price": 1000
      },
      {
        "name": "Mason Shard",
        "availability": 30,
        "rotation": "weekly",
        "amount": 1,
        "price": 1000
      },
      {
        "name": "Drone Parts",
        "availability": 30,
        "rotation": "weekly",
        "amount": 1,
        "price": 1000
      },
      {
        "name": "Lv1 Drone Component Chest",
        "availability": 20,
        "rotation": "weekly",
        "amount": 1,
        "price": 1000
      },
      {
        "name": "Skill Chip Chest (SR)",
        "availability": 5,
        "rotation": "weekly",
        "amount": 1,
        "price": 4000
      },
      {
        "name": "Drone Combat Boost EXP Card",
        "availability": 5,
        "rotation": "weekly",
        "amount": 1,
        "price": 2000
      },
      {
        "name": "8-Hour Shield",
        "availability": 7,
        "rotation": "weekly",
        "amount": 1,
        "price": 7500
      },
      {
        "name": "12-Hour Shield",
        "availability": 2,
        "rotation": "weekly",
        "amount": 1,
        "price": 10000
      },
      {
        "name": "24-Hour Shield",
        "availability": 3,
        "rotation": "weekly",
        "amount": 1,
        "price": 20000
      },
      {
        "name": "Advanced Teleporter",
        "availability": 1,
        "rotation": "weekly",
        "amount": 1,
        "price": 7500
      },
      {
        "name": "Alliance Teleporter",
        "availability": 3,
        "rotation": "weekly",
        "amount": 1,
        "price": 2500
      },
      {
        "name": "Random Teleporter",
        "availability": 3,
        "rotation": "weekly",
        "amount": 1,
        "price": 2500
      },
      {
        "name": "Dielectric Ceramic",
        "availability": 20,
        "rotation": "weekly",
        "amount": 1,
        "price": 800
      },
      {
        "name": "Synthetic Resin",
        "availability": 70,
        "rotation": "weekly",
        "amount": 1,
        "price": 200
      },
      {
        "name": "Superalloy",
        "availability": 100,
        "rotation": "weekly",
        "amount": 1,
        "price": 50
      },
      {
        "name": "Resource Choice Chest (SSR)",
        "availability": 50,
        "rotation": "weekly",
        "amount": 1,
        "price": 12000
      },
      {
        "name": "Survivor's Token",
        "availability": 2500,
        "rotation": "weekly",
        "amount": 1,
        "price": 1
      },
      {
        "name": "Transfer Ticket",
        "availability": 3,
        "rotation": "weekly",
        "amount": 1,
        "price": 4000
      },
      {
        "name": "1h Construction Speed-up",
        "availability": 10,
        "rotation": "weekly",
        "amount": 1,
        "price": 900
      },
      {
        "name": "8h Construction Speed-up",
        "availability": 5,
        "rotation": "weekly",
        "amount": 1,
        "price": 6000
      },
      {
        "name": "1h Training Speed-up",
        "availability": 10,
        "rotation": "weekly",
        "amount": 1,
        "price": 900
      },
      {
        "name": "8h Training Speed-up",
        "availability": 5,
        "rotation": "weekly",
        "amount": 1,
        "price": 6000
      },
      {
        "name": "1h Healing Speed-up",
        "availability": 10,
        "rotation": "weekly",
        "amount": 1,
        "price": 900
      },
      {
        "name": "8h Healing Speed-up",
        "availability": 5,
        "rotation": "weekly",
        "amount": 1,
        "price": 6000
      },
      {
        "name": "1h Research Speed-up",
        "availability": 10,
        "rotation": "weekly",
        "amount": 1,
        "price": 900
      },
      {
        "name": "8h Research Speed-up",
        "availability": 5,
        "rotation": "weekly",
        "amount": 1,
        "price": 6000
      }
    ]
  },
  {
    "id": "campaign-store",
    "name": "Campaign Store",
    "availabilitySchedule": "Restocks weekly on Monday",
    "currency": "Campaign Medals",
    "bricksRate": null,
    "bricksConversionNote": "Campaign Medals are earned through Honorable Campaign missions and Restricted Area Training. They cannot be purchased.",
    "packs": [],
    "items": [
      {
        "name": "Campaign Chest (UR)",
        "availability": 10,
        "rotation": "weekly",
        "amount": 1,
        "price": 200
      },
      {
        "name": "Lv 3 Drone Component Chest",
        "availability": 3,
        "rotation": "weekly",
        "amount": 1,
        "price": 200
      },
      {
        "name": "UR Hero Universal Shard",
        "availability": 10,
        "rotation": "weekly",
        "amount": 1,
        "price": 200
      },
      {
        "name": "Training Certificate",
        "availability": 20,
        "rotation": "weekly",
        "amount": 1,
        "price": 500
      },
      {
        "name": "Battle Data 100K",
        "availability": 25,
        "rotation": "weekly",
        "amount": 1,
        "price": 2000
      },
      {
        "name": "Training Guidebook",
        "availability": 6000,
        "rotation": "weekly",
        "amount": 1,
        "price": 1
      },
      {
        "name": "Overlord Skill Badge",
        "availability": 3000,
        "rotation": "weekly",
        "amount": 1,
        "price": 1
      },
      {
        "name": "Universal Decor Component",
        "availability": 30,
        "rotation": "weekly",
        "amount": 1,
        "price": 200
      },
      {
        "name": "Basic Chip Material",
        "availability": 1,
        "rotation": "weekly",
        "amount": 400,
        "price": 5000
      },
      {
        "name": "Skill Chip Chest (SSR)",
        "availability": 1,
        "rotation": "weekly",
        "amount": 1,
        "price": 10000
      },
      {
        "name": "Universal Exclusive Weapon Shard",
        "availability": 10,
        "rotation": "weekly",
        "amount": 1,
        "price": 300
      },
      {
        "name": "Skill Chip Chest (R)",
        "availability": 20,
        "rotation": "weekly",
        "amount": 1,
        "price": 300
      },
      {
        "name": "Upgrade Ore",
        "availability": 10,
        "rotation": "weekly",
        "amount": 1000,
        "price": 300
      },
      {
        "name": "Drone Parts",
        "availability": 30,
        "rotation": "weekly",
        "amount": 1,
        "price": 300
      },
      {
        "name": "Hero Recruitment Ticket",
        "availability": 30,
        "rotation": "weekly",
        "amount": 1,
        "price": 300
      },
      {
        "name": "Hero EXP Chest (SSR)",
        "availability": 100,
        "rotation": "weekly",
        "amount": 1,
        "price": 300
      },
      {
        "name": "Dielectric Ceramic",
        "availability": 200,
        "rotation": "weekly",
        "amount": 1,
        "price": 300
      },
      {
        "name": "Battle Data 10K",
        "availability": 750,
        "rotation": "weekly",
        "amount": 1,
        "price": 1000
      },
      {
        "name": "Resource Choice Chest (SSR)",
        "availability": 200,
        "rotation": "weekly",
        "amount": 1,
        "price": 500
      },
      {
        "name": "1h Speed-up",
        "availability": 200,
        "rotation": "weekly",
        "amount": 1,
        "price": 500
      }
    ]
  },
  {
    "id": "honor-store",
    "name": "Honor Store",
    "availabilitySchedule": "Restocks monthly on the 1st of the month",
    "currency": "Honor Points",
    "bricksRate": null,
    "bricksConversionNote": "Honor Points are earned by participating in war-related events. They cannot be purchased.",
    "packs": [],
    "items": [
      {
        "name": "Gear Blueprint (MR)",
        "availability": 2,
        "rotation": "monthly",
        "amount": 1,
        "price": 30000
      },
      {
        "name": "Gear Blueprint (UR)",
        "availability": 50,
        "rotation": "monthly",
        "amount": 1,
        "price": 10000
      },
      {
        "name": "Skill Chip Chest (UR)",
        "availability": 1,
        "rotation": "monthly",
        "amount": 1,
        "price": 50000
      },
      {
        "name": "Bond Badge",
        "availability": 20,
        "rotation": "monthly",
        "amount": 1,
        "price": 12000
      },
      {
        "name": "Armament Core",
        "availability": 100,
        "rotation": "monthly",
        "amount": 1,
        "price": 1000
      },
      {
        "name": "Decoration Chest (UR)",
        "availability": 1,
        "rotation": "monthly",
        "amount": 1,
        "price": 50000
      },
      {
        "name": "Universal Decor Component",
        "availability": 150,
        "rotation": "monthly",
        "amount": 1,
        "price": 200
      },
      {
        "name": "UR Hero Universal Shard",
        "availability": 10,
        "rotation": "monthly",
        "amount": 1,
        "price": 3000
      },
      {
        "name": "Drone Parts",
        "availability": 100,
        "rotation": "monthly",
        "amount": 1,
        "price": 800
      },
      {
        "name": "Universal Exclusive Weapon Shard",
        "availability": 25,
        "rotation": "monthly",
        "amount": 1,
        "price": 2500
      },
      {
        "name": "Dielectric Ceramic",
        "availability": 100,
        "rotation": "monthly",
        "amount": 1,
        "price": 800
      },
      {
        "name": "Resource Choice Chest (UR)",
        "availability": 100,
        "rotation": "monthly",
        "amount": 1,
        "price": 4000
      },
      {
        "name": "Hero Recruitment Ticket",
        "availability": 100,
        "rotation": "monthly",
        "amount": 1,
        "price": 2000
      },
      {
        "name": "Emote: Victory Fest",
        "availability": 1,
        "rotation": "monthly",
        "amount": 1,
        "price": 100000
      },
      {
        "name": "Emote: Let's Celebrate",
        "availability": 1,
        "rotation": "monthly",
        "amount": 1,
        "price": 100000
      }
    ]
  }
];

export function getStore(name: string): GameStore | undefined {
  return GAME_STORES.find(s => s.name.toLowerCase().includes(name.toLowerCase()));
}

export function getStoreItemData(): string {
  return GAME_STORES.map(store => {
    const items = (store.items ?? []).map(it => {
      const reduced = it.priceInBricksReduced ? ` (reduced: ${it.priceInBricksReduced})` : '';
      const tag = it.tag ? ` [${it.tag}]` : '';
      return `  ${it.name} x${it.amount} — ${it.priceInBricks} bricks${reduced}${tag} (${it.availability}, ${it.rotation})`;
    }).join('\n');
    const packs = store.packs?.map(pk =>
      `  PACK: ${pk.name} ${pk.priceInBricks} bricks — ${(pk.items ?? []).map(i => `${i.amount}x ${i.name}`).join(', ')}`
    ).join('\n') ?? '';
    const milestones = store.milestones?.map(m =>
      `  MILESTONE at ${m.spend} spent: ${(m.rewards ?? []).map(r => `${r.amount}x ${r.name}`).join(', ')}`
    ).join('\n') ?? '';
    return [
      `[STORE: ${store.name}] Currency: ${store.currency}`,
      store.bricksRate
        ? `  Rate: ${store.bricksRate} bricks/unit` + (store.bricksRateReduced ? `, reduced: ${store.bricksRateReduced} bricks/unit` : '')
        : '',
      items, packs, milestones,
    ].filter(Boolean).join('\n');
  }).join('\n\n');
}
