#!/usr/bin/env ts-node
/**
 * sync-hedge-data.ts
 * Cpt-Hedgehog API → lwtData TypeScript module generator
 *
 * Usage:
 *   npx ts-node scripts/sync-hedge-data.ts
 *
 * What it does:
 *   1. Hits /api/data index to get updatedAt timestamps
 *   2. Compares against .hedge-sync-state.json (last-run timestamps)
 *   3. Only re-fetches endpoints that changed (or --force to skip)
 *   4. Writes/overwrites the relevant lwtData modules in src/lib/
 *   5. Updates .hedge-sync-state.json
 *
 * Flags:
 *   --force     Re-fetch all endpoints regardless of timestamp
 *   --dry-run   Fetch and log, do not write files
 *   --only=<endpoint-path>  Sync only a specific endpoint path
 *
 * Attribution: "Powered by cpt-hedge.com" per partnership agreement.
 *
 * Hero cost endpoints (hero-exp, hero-shards, weapon-shards, gear, skill-medals)
 * are stubbed — Hedge has not deployed these yet. Uncomment sections below when live.
 */

import * as fs from 'fs';
import * as path from 'path';

// ─── CONFIG ──────────────────────────────────────────────────────────────────

const BASE_URL = 'https://cpt-hedge.com';
const API_KEY  = process.env.HEDGE_API_KEY ?? 'h9nqpO2qE2BHxpEfYEOqt189VKzyVeOG';
const OUT_DIR  = path.resolve(__dirname, '../src/lib');
const STATE_FILE = path.resolve(__dirname, '../.hedge-sync-state.json');

const FORCE    = process.argv.includes('--force');
const DRY_RUN  = process.argv.includes('--dry-run');
const ONLY_ARG = process.argv.find(a => a.startsWith('--only='))?.split('=')[1];

// ─── HELPERS ─────────────────────────────────────────────────────────────────

async function fetchJson(endpoint: string): Promise<any> {
  const url = `${BASE_URL}${endpoint}`;
  const res = await fetch(url, { headers: { 'x-api-key': API_KEY } });
  if (!res.ok) throw new Error(`Hedge API ${res.status} on ${endpoint}`);
  return res.json();
}

function writeModule(filename: string, content: string): void {
  const outPath = path.join(OUT_DIR, filename);
  if (DRY_RUN) {
    console.log(`[DRY RUN] Would write: ${outPath} (${content.length} chars)`);
    return;
  }
  fs.writeFileSync(outPath, content, 'utf8');
  console.log(`✅  Wrote: ${filename}`);
}

function loadState(): Record<string, string> {
  try { return JSON.parse(fs.readFileSync(STATE_FILE, 'utf8')); }
  catch { return {}; }
}

function saveState(state: Record<string, string>): void {
  if (!DRY_RUN) fs.writeFileSync(STATE_FILE, JSON.stringify(state, null, 2), 'utf8');
}

function shouldSync(endpoint: string, updatedAt: string, state: Record<string, string>): boolean {
  if (FORCE) return true;
  if (ONLY_ARG && endpoint !== ONLY_ARG) return false;
  return state[endpoint] !== updatedAt;
}

// ─── ATTRIBUTION HEADER ───────────────────────────────────────────────────────

function header(note: string): string {
  return `// Powered by cpt-hedge.com — data licensed per partnership agreement.
// AUTO-GENERATED by scripts/sync-hedge-data.ts — DO NOT EDIT BY HAND.
// ${note}
// Re-run sync script after game patches to refresh data.
`;
}

// ─────────────────────────────────────────────────────────────────────────────
// WRITERS — one per output file
// Each writer receives raw API JSON and returns the full .ts file content.
// ─────────────────────────────────────────────────────────────────────────────

// ── 1. lwtPackData.ts  (stores/packs + stores/passes + stores/currencies) ────

function writePackData(packs: any, passes: any, currencies: any): void {
  const lines: string[] = [
    header('Source: /api/data/stores/packs + /api/data/stores/passes + /api/data/stores/currencies'),
    `// lwtPackData.ts`,
    `// Tiered daily packs, one-time packs, battle passes, brick-to-fiat currency table.`,
    ``,
  ];

  // ── Tiered packs ──
  lines.push(`// ─── TIERED DAILY / ONE-TIME PACKS ──────────────────────────────────────────`);
  lines.push(`export interface PackItem { name: string; amount: number; }`);
  lines.push(`export interface PackTier { priceInBricks: number; items: PackItem[]; }`);
  lines.push(`export interface TieredPack {`);
  lines.push(`  id: string; name: string; availability: string; availabilityType: string;`);
  lines.push(`  tiers: PackTier[];`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`export const TIERED_PACKS: TieredPack[] = ${JSON.stringify(packs.tieredPacks, null, 2)};`);
  lines.push(``);

  // ── Flat / other packs ──
  lines.push(`// ─── FLAT / MISCELLANEOUS PACKS ─────────────────────────────────────────────`);
  lines.push(`export interface FlatPack {`);
  lines.push(`  id: string; name: string; availability: number | string;`);
  lines.push(`  priceInBricks: number; items: PackItem[];`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`export const FLAT_PACKS: FlatPack[] = ${JSON.stringify(packs.otherPacks, null, 2)};`);
  lines.push(``);

  // ── Battle passes ──
  lines.push(`// ─── BATTLE PASSES ───────────────────────────────────────────────────────────`);
  lines.push(`export interface PassTier { name: string; priceInBricks: number; items: PackItem[]; }`);
  lines.push(`export interface BattlePass { id: string; name: string; rotation: string; tiers: PassTier[]; }`);
  lines.push(``);
  lines.push(`export const BATTLE_PASSES: BattlePass[] = ${JSON.stringify(passes.passes, null, 2)};`);
  lines.push(``);

  // ── Currencies ──
  lines.push(`// ─── BRICK-TO-FIAT CURRENCY TABLE ───────────────────────────────────────────`);
  lines.push(`export interface BrickCurrency { currency: string; bricksPerUnit: number; unitsPerBrick: number; }`);
  lines.push(``);
  lines.push(`export const BRICK_CURRENCIES: BrickCurrency[] = ${JSON.stringify(currencies.currencies, null, 2)};`);
  lines.push(``);

  // ── Summary function ──
  lines.push(`// ─── SUMMARY FOR BUDDY SYSTEM PROMPT ────────────────────────────────────────`);
  lines.push(`export function getPackDataSummary(): string {`);
  lines.push(`  const tiered = TIERED_PACKS.map(p => {`);
  lines.push(`    const tierLines = p.tiers.map((t, i) =>`);
  lines.push(`      \`  Tier \${i + 1} (\${t.priceInBricks} bricks): \${t.items.map(it => \`\${it.amount}x \${it.name}\`).join(', ')}\``);
  lines.push(`    ).join('\\n');`);
  lines.push(`    return \`[\${p.name}] (\${p.availability})\\n\${tierLines}\`;`);
  lines.push(`  }).join('\\n\\n');`);
  lines.push(``);
  lines.push(`  const flat = FLAT_PACKS.map(p =>`);
  lines.push(`    \`[\${p.name}] (avail: \${p.availability}) \${p.priceInBricks} bricks: \${p.items.map(it => \`\${it.amount}x \${it.name}\`).join(', ')}\``);
  lines.push(`  ).join('\\n');`);
  lines.push(``);
  lines.push(`  const passList = BATTLE_PASSES.map(p => {`);
  lines.push(`    const tierLines = p.tiers.map(t =>`);
  lines.push(`      \`  \${t.name} (\${t.priceInBricks} bricks): \${t.items.map(it => \`\${it.amount}x \${it.name}\`).join(', ')}\``);
  lines.push(`    ).join('\\n');`);
  lines.push(`    return \`[\${p.name}] (\${p.rotation})\\n\${tierLines}\`;`);
  lines.push(`  }).join('\\n\\n');`);
  lines.push(``);
  lines.push(`  return \``);
  lines.push(`=== PACK DATA (Powered by cpt-hedge.com) ===`);
  lines.push(``);
  lines.push(`--- TIERED DAILY / ONE-TIME PACKS ---`);
  lines.push(`\${tiered}`);
  lines.push(``);
  lines.push(`--- FLAT PACKS ---`);
  lines.push(`\${flat}`);
  lines.push(``);
  lines.push(`--- BATTLE PASSES ---`);
  lines.push(`\${passList}`);
  lines.push(`\`;`);
  lines.push(`}`);

  writeModule('lwtPackData.ts', lines.join('\n'));
}

// ── 2. lwtStoreItemData.ts  (stores/stores) ──────────────────────────────────
// NOTE: Does NOT replace lwtStoresData.ts (strategic advice lives there).
// This file adds raw store item/price/availability data from Hedge.

function writeStoreItemData(stores: any): void {
  const lines: string[] = [
    header('Source: /api/data/stores/stores'),
    `// lwtStoreItemData.ts`,
    `// Raw store item data from cpt-hedge.com. Strategic advice lives in lwtStoresData.ts.`,
    `// This file is the authoritative price/availability reference.`,
    ``,
    `export interface StoreItem {`,
    `  name: string;`,
    `  availability: string;`,
    `  rotation: string;`,
    `  amount: number;`,
    `  price: number;`,
    `  priceInBricks: number;`,
    `  priceInBricksReduced?: number;`,
    `  tag?: string;`,
    `}`,
    ``,
    `export interface StorePack {`,
    `  name: string;`,
    `  priceInBricks: number;`,
    `  items: { name: string; amount: number }[];`,
    `  availability?: string;`,
    `}`,
    ``,
    `export interface StoreMilestone {`,
    `  spend: number;`,
    `  rewards: { name: string; amount: number }[];`,
    `}`,
    ``,
    `export interface GameStore {`,
    `  id: string;`,
    `  name: string;`,
    `  availabilitySchedule: string;`,
    `  currency: string;`,
    `  bricksRate?: number;`,
    `  bricksRateReduced?: number;`,
    `  items: StoreItem[];`,
    `  packs?: StorePack[];`,
    `  milestones?: StoreMilestone[];`,
    `}`,
    ``,
    `export const GAME_STORES: GameStore[] = ${JSON.stringify(stores.stores, null, 2)};`,
    ``,
    `// ─── LOOKUP HELPERS ──────────────────────────────────────────────────────────`,
    ``,
    `export function getStore(name: string): GameStore | undefined {`,
    `  return GAME_STORES.find(s => s.name.toLowerCase().includes(name.toLowerCase()));`,
    `}`,
    ``,
    `export function getStoreItemData(): string {`,
    `  return GAME_STORES.map(store => {`,
    `    const items = store.items.map(it => {`,
    `      const reduced = it.priceInBricksReduced ? \` (reduced: \${it.priceInBricksReduced})\` : '';`,
    `      const tag = it.tag ? \` [\${it.tag}]\` : '';`,
    `      return \`  \${it.name} x\${it.amount} — \${it.priceInBricks} bricks\${reduced}\${tag} (\${it.availability}, \${it.rotation})\`;`,
    `    }).join('\\n');`,
    `    const packs = store.packs?.map(pk =>`,
    `      \`  PACK: \${pk.name} \${pk.priceInBricks} bricks — \${pk.items.map(i => \`\${i.amount}x \${i.name}\`).join(', ')}\``,
    `    ).join('\\n') ?? '';`,
    `    const milestones = store.milestones?.map(m =>`,
    `      \`  MILESTONE at \${m.spend} spent: \${m.rewards.map(r => \`\${r.amount}x \${r.name}\`).join(', ')}\``,
    `    ).join('\\n') ?? '';`,
    `    return [`,
    `      \`[STORE: \${store.name}] Currency: \${store.currency}\`,`,
    `      store.bricksRate ? \`  Rate: \${store.bricksRate} bricks/unit\` + (store.bricksRateReduced ? \`, reduced: \${store.bricksRateReduced} bricks/unit\` : '') : '',`,
    `      items,`,
    `      packs,`,
    `      milestones,`,
    `    ].filter(Boolean).join('\\n');`,
    `  }).join('\\n\\n');`,
    `}`,
  ];

  writeModule('lwtStoreItemData.ts', lines.join('\n'));
}

// ── 3. lwtDroneData.ts  (drone/parts + drone/chips) ──────────────────────────

function writeDroneData(parts: any, chips: any): void {
  const lines: string[] = [
    header('Source: /api/data/drone/parts + /api/data/drone/chips'),
    `// lwtDroneData.ts`,
    `// Drone upgrade costs: parts (300 levels) + skill chips (10 levels).`,
    ``,
    `// ─── DRONE PARTS LEVELS ──────────────────────────────────────────────────────`,
    `export interface DronePartsLevel {`,
    `  level: number;`,
    `  droneParts: number;`,
    `  battleData: number;`,
    `  requiresDroneParts: boolean;`,
    `}`,
    ``,
    `export const DRONE_PARTS_LEVELS: DronePartsLevel[] = ${JSON.stringify(parts.levels, null, 2)};`,
    ``,
    `export const DRONE_SPECIAL_UNLOCKS: { level: number; description: string }[] = ${JSON.stringify(parts.specialUnlocks ?? [], null, 2)};`,
    ``,
    `// ─── DRONE CHIP LEVELS ───────────────────────────────────────────────────────`,
    `export interface DroneChipLevel {`,
    `  level: number;`,
    `  chips: number;`,
    `}`,
    ``,
    `export const DRONE_CHIP_LEVELS: DroneChipLevel[] = ${JSON.stringify(chips.levels, null, 2)};`,
    ``,
    `export const DRONE_CHIP_META = ${JSON.stringify(chips.meta, null, 2)};`,
    ``,
    `// ─── AGGREGATE HELPERS ───────────────────────────────────────────────────────`,
    ``,
    `/** Total Battle Data cost to reach a target drone level from level 1 */`,
    `export function droneBattleDataToLevel(targetLevel: number): number {`,
    `  return DRONE_PARTS_LEVELS`,
    `    .filter(l => l.level <= targetLevel)`,
    `    .reduce((sum, l) => sum + l.battleData, 0);`,
    `}`,
    ``,
    `/** Total Drone Parts cost to reach a target drone level from level 1 */`,
    `export function dronePartsToLevel(targetLevel: number): number {`,
    `  return DRONE_PARTS_LEVELS`,
    `    .filter(l => l.level <= targetLevel)`,
    `    .reduce((sum, l) => sum + l.droneParts, 0);`,
    `}`,
    ``,
    `/** Total Skill Chips to reach a target chip level */`,
    `export function droneChipsToLevel(targetLevel: number): number {`,
    `  return DRONE_CHIP_LEVELS`,
    `    .filter(l => l.level <= targetLevel)`,
    `    .reduce((sum, l) => sum + l.chips, 0);`,
    `}`,
    ``,
    `export function getDroneDataSummary(): string {`,
    `  const totalParts = DRONE_PARTS_LEVELS.reduce((s, l) => s + l.droneParts, 0);`,
    `  const totalBD   = DRONE_PARTS_LEVELS.reduce((s, l) => s + l.battleData, 0);`,
    `  const totalChips = DRONE_CHIP_META.totalChipsForMaxLevel;`,
    ``,
    `  const specialUnlockStr = DRONE_SPECIAL_UNLOCKS.length`,
    `    ? DRONE_SPECIAL_UNLOCKS.map(u => \`  Level \${u.level}: \${u.description}\`).join('\\n')`,
    `    : '  None documented';`,
    ``,
    `  // Sample breakpoints for Buddy context`,
    `  const breakpoints = [50, 100, 150, 200, 250, 300].map(lvl => {`,
    `    const bd = droneBattleDataToLevel(lvl);`,
    `    const dp = dronePartsToLevel(lvl);`,
    `    return \`  Level \${lvl}: \${dp.toLocaleString()} Parts + \${bd.toLocaleString()} Battle Data\`;`,
    `  }).join('\\n');`,
    ``,
    `  return \``,
    `=== DRONE DATA (Powered by cpt-hedge.com) ===`,
    ``,
    `Total levels: \${DRONE_PARTS_LEVELS.length}`,
    `To max (level \${DRONE_PARTS_LEVELS.length}): \${totalParts.toLocaleString()} Drone Parts + \${totalBD.toLocaleString()} Battle Data`,
    ``,
    `Cumulative cost breakpoints:`,
    `\${breakpoints}`,
    ``,
    `Special unlocks at:`,
    `\${specialUnlockStr}`,
    ``,
    `Skill Chips — max level: \${DRONE_CHIP_META.maxLevel}`,
    `Total chips to max: \${totalChips}`,
    `Chip cost per level: \${DRONE_CHIP_LEVELS.map(l => \`L\${l.level}: \${l.chips}\`).join(' | ')}`,
    `\`;`,
    `}`,
  ];

  writeModule('lwtDroneData.ts', lines.join('\n'));
}

// ── 4. lwtT11ArmamentData.ts  (units/t11) ────────────────────────────────────
// Separate from lwtT11Data.ts (strategic). This is the raw cost table.

function writeT11ArmamentData(t11: any): void {
  const lines: string[] = [
    header('Source: /api/data/units/t11'),
    `// lwtT11ArmamentData.ts`,
    `// Raw T11 armament upgrade costs from cpt-hedge.com.`,
    `// Strategic guide lives in lwtT11Data.ts — do not merge.`,
    ``,
    `// ─── TYPES ───────────────────────────────────────────────────────────────────`,
    `export interface ArmamentLevel {`,
    `  level: number;`,
    `  materials: number;`,
    `  cores: number;`,
    `  oil?: number;`,
    `}`,
    ``,
    `export interface ArmamentStarTier {`,
    `  levelStep: number;`,
    `  levels: ArmamentLevel[];`,
    `}`,
    ``,
    `export interface ArmamentPiece {`,
    `  base: ArmamentStarTier;`,
    `  star1: ArmamentStarTier | null;`,
    `  star2: ArmamentStarTier | null;`,
    `  star3: ArmamentStarTier | null;`,
    `  star4: ArmamentStarTier | null;`,
    `}`,
    ``,
    `// ─── DATA ────────────────────────────────────────────────────────────────────`,
    `export const T11_ARMAMENT_PIECES: Record<string, ArmamentPiece> = ${JSON.stringify(t11.pieces, null, 2)};`,
    ``,
    `export const T11_ARMAMENT_UNLOCK_REQUIREMENTS: Record<string, { materials: number; cores: number; oil: number } | null> = ${JSON.stringify(t11.unlockRequirements, null, 2)};`,
    ``,
    `export const T11_ARMAMENT_META = ${JSON.stringify(t11.meta, null, 2)};`,
    ``,
    `// ─── AGGREGATE HELPERS ───────────────────────────────────────────────────────`,
    ``,
    `type StarTier = 'base' | 'star1' | 'star2' | 'star3' | 'star4';`,
    `const STAR_TIERS: StarTier[] = ['base', 'star1', 'star2', 'star3', 'star4'];`,
    `const PIECE_NAMES = ['helmet', 'bodyArmor', 'accessories', 'weapon'] as const;`,
    ``,
    `/** Total materials to fully research one piece through all available star tiers */`,
    `export function pieceResearchCost(pieceName: string): { materials: number; cores: number } {`,
    `  const piece = T11_ARMAMENT_PIECES[pieceName];`,
    `  if (!piece) return { materials: 0, cores: 0 };`,
    `  let materials = 0, cores = 0;`,
    `  for (const star of STAR_TIERS) {`,
    `    const tier = piece[star];`,
    `    if (!tier) continue;`,
    `    for (const lvl of tier.levels) { materials += lvl.materials; cores += lvl.cores; }`,
    `  }`,
    `  return { materials, cores };`,
    `}`,
    ``,
    `/** Total research cost across all four pieces for a given star tier */`,
    `export function allPiecesStarCost(star: StarTier): { materials: number; cores: number } {`,
    `  let materials = 0, cores = 0;`,
    `  for (const name of PIECE_NAMES) {`,
    `    const tier = T11_ARMAMENT_PIECES[name]?.[star];`,
    `    if (!tier) continue;`,
    `    for (const lvl of tier.levels) { materials += lvl.materials; cores += lvl.cores; }`,
    `  }`,
    `  return { materials, cores };`,
    `}`,
    ``,
    `export function getT11ArmamentSummary(): string {`,
    `  const pieceRows = PIECE_NAMES.map(name => {`,
    `    const cost = pieceResearchCost(name);`,
    `    return \`  \${name}: \${cost.materials.toLocaleString()} materials + \${cost.cores.toLocaleString()} cores (all stars)\`;`,
    `  }).join('\\n');`,
    ``,
    `  const starRows = STAR_TIERS.map(star => {`,
    `    const unlock = T11_ARMAMENT_UNLOCK_REQUIREMENTS[star];`,
    `    const research = allPiecesStarCost(star);`,
    `    if (!research.materials && !unlock) return null;`,
    `    const unlockStr = unlock`,
    `      ? \` + one-time unlock: \${unlock.materials.toLocaleString()} mats, \${unlock.cores} cores, \${unlock.oil?.toLocaleString() ?? 0} oil\``,
    `      : '';`,
    `    return \`  \${star}: research all 4 pieces = \${research.materials.toLocaleString()} mats + \${research.cores} cores\${unlockStr}\`;`,
    `  }).filter(Boolean).join('\\n');`,
    ``,
    `  return \``,
    `=== T11 ARMAMENT COST DATA (Powered by cpt-hedge.com) ===`,
    ``,
    `Research cost by piece (all stars combined):`,
    `\${pieceRows}`,
    ``,
    `Research + unlock cost by star tier (all 4 pieces):`,
    `\${starRows}`,
    ``,
    `NOTE: star3 and star4 data not yet available from Hedge.`,
    `\`;`,
    `}`,
  ];

  writeModule('lwtT11ArmamentData.ts', lines.join('\n'));
}

// ── 5. lwtOverlordCostData.ts  (overlord/training + /promotion + /skills) ────
// Augments lwtOverlordData.ts (strategic). Raw cost tables only.

function writeOverlordCostData(training: any, promotion: any, skills: any): void {
  const lines: string[] = [
    header('Source: /api/data/overlord/training + /overlord/promotion + /overlord/skills'),
    `// lwtOverlordCostData.ts`,
    `// Raw Overlord cost tables from cpt-hedge.com.`,
    `// Strategic guide + deployment requirements live in lwtOverlordData.ts.`,
    ``,
    `// ─── TRAINING COSTS (per level, per specialization — 3 specializations, 800 levels each) ─`,
    `export interface OverlordTrainingLevel {`,
    `  level: number;`,
    `  guidebooks: number;`,
    `  certificates: number;`,
    `}`,
    ``,
    `// training is a flat array — same cost applies to each of the 3 specializations`,
    `export const OVERLORD_TRAINING_LEVELS: OverlordTrainingLevel[] = ${JSON.stringify(training.training, null, 2)};`,
    ``,
    `export const OVERLORD_BOND_RATINGS: {`,
    `  name: string; tier: number; badges: number; training_unlock?: number;`,
    `}[] = ${JSON.stringify(training.bondRatings, null, 2)};`,
    ``,
    `export const OVERLORD_TRAINING_META = ${JSON.stringify(training.meta, null, 2)};`,
    ``,
    `// ─── PROMOTION LEVELS ────────────────────────────────────────────────────────`,
    `export interface OverlordPromoLevel {`,
    `  name: string;`,
    `  level: number;`,
    `  shards: number;`,
    `  unlocks: { name: string; stars: number }[];`,
    `}`,
    ``,
    `export const OVERLORD_PROMO_LEVELS: OverlordPromoLevel[] = ${JSON.stringify(promotion.levels, null, 2)};`,
    ``,
    `export const OVERLORD_PROMO_META = ${JSON.stringify(promotion.meta, null, 2)};`,
    ``,
    `// ─── SKILL UPGRADE COSTS ─────────────────────────────────────────────────────`,
    `export interface OverlordSkillLevel {`,
    `  level: number;`,
    `  badges: number;`,
    `}`,
    ``,
    `export const OVERLORD_SKILL_LEVELS: OverlordSkillLevel[] = ${JSON.stringify(skills.levels, null, 2)};`,
    ``,
    `export const OVERLORD_SKILL_META = ${JSON.stringify(skills.meta ?? {}, null, 2)};`,
    ``,
    `// ─── AGGREGATE HELPERS ───────────────────────────────────────────────────────`,
    ``,
    `/** Guidebooks + Certificates to train ONE specialization from level 1 to targetLevel */`,
    `export function trainingCostToLevel(targetLevel: number): { guidebooks: number; certificates: number } {`,
    `  return OVERLORD_TRAINING_LEVELS`,
    `    .filter(l => l.level <= targetLevel)`,
    `    .reduce((sum, l) => ({ guidebooks: sum.guidebooks + l.guidebooks, certificates: sum.certificates + l.certificates }), { guidebooks: 0, certificates: 0 });`,
    `}`,
    ``,
    `/** Total guidebooks + certificates for ALL THREE specializations to targetLevel */`,
    `export function totalTrainingCostToLevel(targetLevel: number): { guidebooks: number; certificates: number } {`,
    `  const single = trainingCostToLevel(targetLevel);`,
    `  return { guidebooks: single.guidebooks * 3, certificates: single.certificates * 3 };`,
    `}`,
    ``,
    `/** Total Overlord Skill Badges to upgrade one skill from level 1 to targetLevel */`,
    `export function skillBadgesToLevel(targetLevel: number): number {`,
    `  return OVERLORD_SKILL_LEVELS`,
    `    .filter(l => l.level <= targetLevel)`,
    `    .reduce((sum, l) => sum + l.badges, 0);`,
    `}`,
    ``,
    `export function getOverlordCostSummary(): string {`,
    `  const deployAt = totalTrainingCostToLevel(100);`,
    `  const maxTrainLevel = OVERLORD_TRAINING_META.maxTrainingLevel;`,
    `  const maxTrainAll = totalTrainingCostToLevel(maxTrainLevel);`,
    `  const totalSkillBadges = skillBadgesToLevel(OVERLORD_SKILL_LEVELS.length);`,
    `  const totalPromoShards = OVERLORD_PROMO_LEVELS.reduce((s, l) => s + l.shards, 0);`,
    ``,
    `  const bondMilestones = OVERLORD_BOND_RATINGS`,
    `    .filter(b => b.training_unlock)`,
    `    .map(b => \`  \${b.name} (tier \${b.tier}): requires all specs at level \${b.training_unlock}\`)`,
    `    .join('\\n');`,
    ``,
    `  return \``,
    `=== OVERLORD COST DATA (Powered by cpt-hedge.com) ===`,
    ``,
    `Training — to deploy (all 3 specs to level 100):`,
    `  Guidebooks:    \${deployAt.guidebooks.toLocaleString()}`,
    `  Certificates:  \${deployAt.certificates.toLocaleString()}`,
    ``,
    `Training — to max (all 3 specs to level \${maxTrainLevel}):`,
    `  Guidebooks:    \${maxTrainAll.guidebooks.toLocaleString()}`,
    `  Certificates:  \${maxTrainAll.certificates.toLocaleString()}`,
    ``,
    `Bond Rating milestones (training unlock gates):`,
    `\${bondMilestones}`,
    ``,
    `Promotion — total Overlord Shards to max: \${totalPromoShards.toLocaleString()}`,
    ``,
    `Skills — total Skill Badges to max all levels: \${totalSkillBadges.toLocaleString()}`,
    `Per-level badge cost: \${OVERLORD_SKILL_LEVELS.map(l => \`L\${l.level}:\${l.badges}\`).join(' | ')}`,
    `\`;`,
    `}`,
  ];

  writeModule('lwtOverlordCostData.ts', lines.join('\n'));
}

// ── 6. lwtBuildingCostData.ts  (buildings/core + buildings/season-1..5) ───────

function writeBuildingCostData(core: any, seasons: any[]): void {
  const lines: string[] = [
    header('Source: /api/data/buildings/core + /api/data/buildings/season-1 through season-5'),
    `// lwtBuildingCostData.ts`,
    `// Raw building upgrade costs from cpt-hedge.com.`,
    `// Strategic upgrade priority lives in lwtBuildingData.ts — do not merge.`,
    ``,
    `// ─── TYPES ───────────────────────────────────────────────────────────────────`,
    `export interface BuildingLevel {`,
    `  level: number;`,
    `  rss: Record<string, number>;`,
    `  time: string;`,
    `  power: number;`,
    `  [key: string]: any; // extra stat fields vary per building`,
    `}`,
    ``,
    `export interface BuildingCostEntry {`,
    `  name: string;`,
    `  levels: BuildingLevel[];`,
    `}`,
    ``,
    `// ─── CORE BUILDINGS ──────────────────────────────────────────────────────────`,
    `export const CORE_BUILDINGS: BuildingCostEntry[] = ${JSON.stringify(core.buildings, null, 2)};`,
    ``,
  ];

  // Season buildings
  for (let i = 0; i < seasons.length; i++) {
    const seasonNum = i + 1;
    const varName = `SEASON_${seasonNum}_BUILDINGS`;
    lines.push(`// ─── SEASON ${seasonNum} BUILDINGS ──────────────────────────────────────────────────`);
    lines.push(`export const ${varName}: BuildingCostEntry[] = ${JSON.stringify(seasons[i]?.buildings ?? [], null, 2)};`);
    lines.push(``);
  }

  lines.push(`// ─── LOOKUP HELPERS ──────────────────────────────────────────────────────────`);
  lines.push(``);
  lines.push(`export function getCoreBuilding(name: string): BuildingCostEntry | undefined {`);
  lines.push(`  return CORE_BUILDINGS.find(b => b.name.toLowerCase().includes(name.toLowerCase()));`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`/** Upgrade cost for a specific building at a specific level */`);
  lines.push(`export function getBuildingLevelCost(buildingName: string, level: number): BuildingLevel | undefined {`);
  lines.push(`  const building = getCoreBuilding(buildingName);`);
  lines.push(`  return building?.levels.find(l => l.level === level);`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`/** Total food+iron+gold cost to upgrade a building from currentLevel to targetLevel */`);
  lines.push(`export function buildingUpgradeCost(`);
  lines.push(`  buildingName: string,`);
  lines.push(`  fromLevel: number,`);
  lines.push(`  toLevel: number`);
  lines.push(`): { food: number; iron: number; gold: number; timeStr: string } {`);
  lines.push(`  const building = getCoreBuilding(buildingName);`);
  lines.push(`  if (!building) return { food: 0, iron: 0, gold: 0, timeStr: '?' };`);
  lines.push(`  const levels = building.levels.filter(l => l.level > fromLevel && l.level <= toLevel);`);
  lines.push(`  return levels.reduce(`);
  lines.push(`    (sum, l) => ({`);
  lines.push(`      food: sum.food + (l.rss.food ?? 0),`);
  lines.push(`      iron: sum.iron + (l.rss.iron ?? 0),`);
  lines.push(`      gold: sum.gold + (l.rss.gold ?? 0),`);
  lines.push(`      timeStr: 'see individual levels',`);
  lines.push(`    }),`);
  lines.push(`    { food: 0, iron: 0, gold: 0, timeStr: '' }`);
  lines.push(`  );`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`export function getBuildingCostSummary(): string {`);
  lines.push(`  const coreNames = CORE_BUILDINGS.map(b => \`  \${b.name} (\${b.levels.length} levels)\`).join('\\n');`);
  lines.push(`  const s1Names = SEASON_1_BUILDINGS.map(b => \`  \${b.name} (\${b.levels.length} levels)\`).join('\\n');`);
  lines.push(`  return \``);
  lines.push(`=== BUILDING COST DATA (Powered by cpt-hedge.com) ===`);
  lines.push(``);
  lines.push(`Core buildings (\${CORE_BUILDINGS.length} total):`);
  lines.push(`\${coreNames}`);
  lines.push(``);
  lines.push(`Season 1 buildings:`);
  lines.push(`\${s1Names}`);
  lines.push(``);
  lines.push(`Use getBuildingLevelCost(name, level) to look up exact costs.`);
  lines.push(`Use buildingUpgradeCost(name, fromLevel, toLevel) for range totals.`);
  lines.push(`\`;`);
  lines.push(`}`);

  writeModule('lwtBuildingCostData.ts', lines.join('\n'));
}

// ─── STUBS FOR UNDEPLOYED ENDPOINTS ──────────────────────────────────────────
// hero-exp, hero-shards, weapon-shards, gear, skill-medals → 404 as of sync date
// Uncomment the heroWriter call in main() when Hedge deploys these routes.

function writeHeroCostDataStub(): void {
  const content = `// Powered by cpt-hedge.com — data licensed per partnership agreement.
// AUTO-GENERATED by scripts/sync-hedge-data.ts — DO NOT EDIT BY HAND.
// lwtHeroCostData.ts — STUB: hero cost endpoints not yet deployed by Hedge.
// Endpoints returning 404: /api/data/hero-exp, /api/data/hero-shards,
//   /api/data/weapon-shards, /api/data/gear, /api/data/skill-medals
// TODO: uncomment heroWriter block in sync-hedge-data.ts once Hedge deploys.

export const HERO_COST_DATA_STATUS = 'pending — awaiting Hedge API deployment';

export function getHeroCostDataSummary(): string {
  return '// Hero cost data not yet available — Hedge endpoints pending deployment.';
}
`;
  writeModule('lwtHeroCostData.ts', content);
}

// ─── MAIN ─────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  console.log(`\n🚀 Hedge Data Sync — ${new Date().toISOString()}`);
  if (DRY_RUN) console.log('   [DRY RUN — no files will be written]');
  if (FORCE)   console.log('   [FORCE — ignoring timestamps, re-fetching all]');
  if (ONLY_ARG) console.log(`   [ONLY: ${ONLY_ARG}]`);
  console.log('');

  // 1. Fetch index
  console.log('📡 Fetching data index…');
  const index = await fetchJson('/api/data');
  const state = loadState();
  const newState: Record<string, string> = { ...state };

  // Build a lookup: path → updatedAt
  const tsMap: Record<string, string> = {};
  for (const ep of index.endpoints) {
    tsMap[ep.path] = ep.updatedAt;
  }

  // 2. Determine what needs syncing
  const needsSync = (p: string) => shouldSync(p, tsMap[p] ?? '', state);

  // ── PACK DATA (packs + passes + currencies) ──────────────────────────────
  const packPaths = ['/api/data/stores/packs', '/api/data/stores/passes', '/api/data/stores/currencies'];
  if (packPaths.some(needsSync)) {
    console.log('📦 Syncing pack data…');
    const [packs, passes, currencies] = await Promise.all(packPaths.map(fetchJson));
    writePackData(packs, passes, currencies);
    packPaths.forEach(p => { newState[p] = tsMap[p]; });
  } else {
    console.log('⏭️  Pack data up to date, skipping.');
  }

  // ── STORE ITEM DATA ───────────────────────────────────────────────────────
  const storePath = '/api/data/stores/stores';
  if (needsSync(storePath)) {
    console.log('🏪 Syncing store item data…');
    const stores = await fetchJson(storePath);
    writeStoreItemData(stores);
    newState[storePath] = tsMap[storePath];
  } else {
    console.log('⏭️  Store item data up to date, skipping.');
  }

  // ── DRONE DATA ────────────────────────────────────────────────────────────
  const dronePaths = ['/api/data/drone/parts', '/api/data/drone/chips'];
  if (dronePaths.some(needsSync)) {
    console.log('🤖 Syncing drone data…');
    const [parts, chips] = await Promise.all(dronePaths.map(fetchJson));
    writeDroneData(parts, chips);
    dronePaths.forEach(p => { newState[p] = tsMap[p]; });
  } else {
    console.log('⏭️  Drone data up to date, skipping.');
  }

  // ── T11 ARMAMENT DATA ─────────────────────────────────────────────────────
  const t11Path = '/api/data/units/t11';
  if (needsSync(t11Path)) {
    console.log('⚔️  Syncing T11 armament data…');
    const t11 = await fetchJson(t11Path);
    writeT11ArmamentData(t11);
    newState[t11Path] = tsMap[t11Path];
  } else {
    console.log('⏭️  T11 armament data up to date, skipping.');
  }

  // ── OVERLORD COST DATA ────────────────────────────────────────────────────
  const ovPaths = ['/api/data/overlord/training', '/api/data/overlord/promotion', '/api/data/overlord/skills'];
  if (ovPaths.some(needsSync)) {
    console.log('🦍 Syncing Overlord cost data…');
    const [training, promotion, skills_] = await Promise.all(ovPaths.map(fetchJson));
    writeOverlordCostData(training, promotion, skills_);
    ovPaths.forEach(p => { newState[p] = tsMap[p]; });
  } else {
    console.log('⏭️  Overlord cost data up to date, skipping.');
  }

  // ── BUILDING COST DATA (core + 5 seasons) ────────────────────────────────
  const bldCorePath = '/api/data/buildings/core';
  const bldSeasonPaths = [1, 2, 3, 4, 5].map(n => `/api/data/buildings/season-${n}`);
  const allBldPaths = [bldCorePath, ...bldSeasonPaths];
  if (allBldPaths.some(needsSync)) {
    console.log('🏗️  Syncing building cost data…');
    const [core, ...seasonResults] = await Promise.all(
      [fetchJson(`${bldCorePath}?per_page=500`), ...bldSeasonPaths.map(p => fetchJson(`${p}?per_page=500`))]
    );
    writeBuildingCostData(core, seasonResults);
    allBldPaths.forEach(p => { newState[p] = tsMap[p]; });
  } else {
    console.log('⏭️  Building cost data up to date, skipping.');
  }

  // ── HERO COST DATA (stub — endpoints 404) ────────────────────────────────
  // TODO: When Hedge deploys hero endpoints, replace this with:
  // const heroPaths = ['/api/data/hero-exp', '/api/data/hero-shards', '/api/data/weapon-shards', '/api/data/gear', '/api/data/skill-medals'];
  // if (heroPaths.some(needsSync)) { ... fetch + writeHeroCostData(exp, shards, weaponShards, gear, skillMedals); }
  const heroStubPath = path.join(OUT_DIR, 'lwtHeroCostData.ts');
  if (!fs.existsSync(heroStubPath)) {
    console.log('⚠️  Hero cost endpoints not deployed — writing stub file.');
    writeHeroCostDataStub();
  } else {
    console.log('⏭️  Hero cost stub already exists, skipping.');
  }

  // 3. Save state
  saveState(newState);
  console.log('\n✅  Sync complete. State saved to .hedge-sync-state.json');
  console.log('📋  Files written to src/lib/:');
  console.log('    lwtPackData.ts');
  console.log('    lwtStoreItemData.ts');
  console.log('    lwtDroneData.ts');
  console.log('    lwtT11ArmamentData.ts');
  console.log('    lwtOverlordCostData.ts');
  console.log('    lwtBuildingCostData.ts');
  console.log('    lwtHeroCostData.ts (stub — hero endpoints pending Hedge deployment)');
  console.log('\n⚠️  REMINDER: Ping Hedge about hero-exp, hero-shards, weapon-shards, gear, skill-medals (all 404)');
}

main().catch(err => {
  console.error('\n❌ Sync failed:', err);
  process.exit(1);
});